import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { CatalogSchema } from '../../src/lib/domain/schema-parts/catalog.js';
import { canonicalDigest, digestWithoutField } from '../../src/lib/domain/canonical-json.js';
import { calculateContentWorkManifestScopeDigest } from '../../src/lib/validation/content-work-manifest.js';
import { deriveCatalogEvidenceTrustContext } from '../../src/lib/catalog/evidence-inventory.js';
import { catalogContentDigest } from '../../src/lib/catalog/build-catalog.js';
import { renderProblemAuthoringDocument } from '../../src/lib/authoring/problem-authoring-document.js';
import { ATCODER_PROBLEMS_SOURCES } from '../../src/lib/corpus/atcoder-problems-metrics.js';
import { makeTrustedCatalog } from './trusted-catalog.js';
import {
  FULL_RELEASE_CATALOG_PATH,
  FULL_RELEASE_EVIDENCE_PATH,
  FULL_RELEASE_MERGE_REVIEW_PATH,
} from '../../scripts/release/validate-full-release.js';

const sha = (character: string) => character.repeat(64);
const fileDigest = (value: string | Buffer) => createHash('sha256').update(value).digest('hex');

export const releaseContentInventory = async (
  root: string,
  directory = 'src/content',
): Promise<{ path: string; sha256: string; byteLength: number }[]> => {
  const entries = await readdir(path.join(root, directory), { withFileTypes: true });
  const nested = await Promise.all(
    entries.map(async (entry) => {
      const file = `${directory}/${entry.name}`;
      if (entry.isDirectory()) return releaseContentInventory(root, file);
      const bytes = await readFile(path.join(root, file));
      return [{ path: file, sha256: fileDigest(bytes), byteLength: bytes.length }];
    }),
  );
  return nested.flat().sort((a, b) => a.path.localeCompare(b.path, 'en'));
};

/** Synthetic release evidence is confined to the test repository. No production
 * review, check, or publication record is generated by this fixture.
 */
export const makeFullReleaseFixture = async (repositoryRoot: string) => {
  const writeText = async (file: string, value: string) => {
    await mkdir(path.dirname(path.join(repositoryRoot, file)), { recursive: true });
    await writeFile(path.join(repositoryRoot, file), value);
    return fileDigest(value);
  };
  const writeJson = (file: string, value: unknown) =>
    writeText(file, `${JSON.stringify(value, null, 2)}\n`);
  const catalog = CatalogSchema.parse(
    JSON.parse(
      JSON.stringify(makeTrustedCatalog({})).replaceAll('abc212-x45', 'abc212-e'),
    ) as unknown,
  );
  const authoring = catalog.authoringUnits[0];
  const unit = catalog.learningUnits[0];
  const problem = catalog.problems[0];
  if (!authoring || !unit || !problem) throw new Error('Missing fixture owners.');
  const example = unit.examples[0];
  const exercise = authoring.exercises[0];
  const sourceRevisionId = authoring.sourceRevisionIds[0];
  if (!example || !exercise || !sourceRevisionId) throw new Error('Missing fixture blocks.');
  authoring.docPath = 'src/content/docs/problems/abc212-e.md';
  // Exercise both the JSON reader and the binary canonical-file reader beyond
  // the current full corpus's 4.8 MB of serialized authoring units.
  authoring.sections.reasoning = 'Fixture reasoning. '.repeat(350_000);
  authoring.examples = [
    {
      ...example,
      key: 'taxonomy-integration',
      learningUnitIds: [unit.id],
      executionTarget: null,
    },
  ];
  exercise.key = 'taxonomy-integration';
  unit.contentPhase = 'full_authoring';
  unit.ownedTagIds = unit.tagIds;
  unit.ownedLearningOutcomeIds = unit.learningOutcomeIds;
  unit.directProblemIds = unit.problemIds;
  const basePlacement = {
    id: 'placement-abc212-e',
    problemId: authoring.problemId,
    policyVersion: '1.0.0',
    kind: 'full' as const,
    primaryProblemId: null,
    sharedOutcomeIds: [],
    additionalElement: null,
    comparison: {
      method: 'Fixture method.',
      proof: 'Fixture proof.',
      complexity: 'O(1).',
      constraints: 'Fixture constraints.',
      prerequisites: 'Fixture prerequisites.',
      implementation: 'Fixture implementation.',
    },
    rationale: 'Fixture placement.',
    evidenceIds: ['evidence-official-analysis'],
  };
  catalog.placements = [basePlacement];
  problem.placementId = basePlacement.id;
  const evidenceRef = {
    problemId: authoring.problemId,
    claimPath: '/reasoningPath/keyInsights/0',
    evidenceIds: ['evidence-official-analysis'],
    sourceRevisionIds: authoring.sourceRevisionIds,
  };
  const placement = {
    ...basePlacement,
    problemId: authoring.problemId,
    primaryOutcomeId: 'outcome-graphs',
    additionalPrimaryOutcomeIds: [],
    supportingOutcomeIds: [],
    primaryTagIds: ['tag-graphs'],
    supportingTagIds: [],
    adHocElements: [],
    claimDispositions: [
      {
        claimRef: evidenceRef,
        kind: 'primary',
        tagIds: ['tag-graphs'],
        rationale: 'Fixture classification.',
      },
    ],
    analysisEvidenceRefs: [evidenceRef],
  };
  const indexPath = 'src/content/indexes/taxonomy.json';
  const impact = {
    id: 'impact-fixture',
    sourceRevisionId,
    sourceRevisionIds: authoring.sourceRevisionIds,
    changeSummary: 'Fixture taxonomy integration.',
    verificationStatus: 'pending' as const,
    derivedIndexPaths: [indexPath],
    affectedContentLocators: [
      { ownerType: 'problem' as const, problemId: authoring.problemId, path: 'sections.reasoning' },
      {
        ownerType: 'problem' as const,
        problemId: authoring.problemId,
        path: 'examples.taxonomy-integration',
      },
      {
        ownerType: 'problem' as const,
        problemId: authoring.problemId,
        path: 'exercises.taxonomy-integration',
      },
      {
        ownerType: 'problem' as const,
        problemId: authoring.problemId,
        path: 'exercises.taxonomy-integration.answer',
      },
      {
        ownerType: 'problem_placement' as const,
        problemId: authoring.problemId,
        path: 'src/content/policies/problem-placements.json',
      },
    ],
  };
  catalog.correctionImpacts = [{ ...impact, verificationStatus: 'verified' }];
  const previewSubject = {
    id: impact.id,
    integrationPreviewEntityIds: ['preview-graphs'],
    sourceRevisionIds: impact.sourceRevisionIds,
    changeSummary: impact.changeSummary,
    affectedProblemIds: [authoring.problemId],
    affectedLearningUnitCandidateIds: [],
    surfaceAssessments: [
      ...['body', 'example', 'exercise', 'answer', 'placement', 'derived_index'].map((surface) => ({
        ownerType: 'problem',
        problemId: authoring.problemId,
        surface,
        disposition: 'materialize_change',
        rationale: 'Fixture integration.',
        evidenceRefs: [evidenceRef],
      })),
      {
        ownerType: 'derived_index',
        path: indexPath,
        surface: 'index',
        disposition: 'materialize_change',
        rationale: 'Fixture index.',
        evidenceRefs: [evidenceRef],
      },
    ],
    derivedIndexPaths: [indexPath],
    canonicalMaterializationTask: 'T049',
    coverageStatus: 'complete',
  };
  const previewTaxonomyChanges = [
    {
      ...previewSubject,
      verificationStatus: 'pending',
      impactSubjectDigest: canonicalDigest(previewSubject),
    },
  ];
  const policy = {
    schemaVersion: '1.0.0',
    sourceBuild: { id: 'build-fixture', digest: sha('a'), acceptedAt: '2026-07-17T03:00:00+09:00' },
    placements: [placement],
    decisionTable: {
      path: 'src/content/policies/problem-placement.json',
      version: '1.0.0',
      digest: sha('a'),
    },
    correctionImpacts: [impact],
    previewTaxonomyChanges,
    placementDigest: canonicalDigest([placement]),
    correctionImpactDigest: canonicalDigest([impact]),
    previewTaxonomyChangeDigest: canonicalDigest(previewTaxonomyChanges),
  };
  const prerequisites = {
    schemaVersion: '1.0.0',
    sourceBuild: policy.sourceBuild,
    tagPrerequisites: [],
    learningOutcomePrerequisites: [],
    learningUnitPrerequisites: [],
    tagDagDigest: canonicalDigest([]),
    learningOutcomeDagDigest: canonicalDigest([]),
    learningUnitDagDigest: canonicalDigest([]),
  };
  const writeAuthoring = () =>
    writeText(
      authoring.docPath,
      renderProblemAuthoringDocument(authoring, 'Fixture problem', {
        home: 'Fixture graphs',
        outcomes: [],
        sources: [],
        prerequisites: [],
      }),
    );
  await writeAuthoring();
  await writeText(
    unit.docPath,
    '# Fixture graphs\n\n## 考え方\n\nTrace the invariant.\n\n## 成立条件と計算量\n\nO(1).\n',
  );
  for (const [collection, directory] of [
    ['problems', 'problems'],
    ['contests', 'contests'],
    ['tags', 'tags'],
    ['learningOutcomes', 'learning-outcomes'],
    ['learningUnits', 'learning-units'],
    ['techniqueInventory', 'technique-inventory'],
    ['sources', 'sources'],
  ] as const) {
    for (const [index, entity] of catalog[collection].entries())
      await writeJson(`src/content/${directory}/${String(index)}.json`, entity);
  }
  await writeJson('src/content/policies/problem-placements.json', policy);
  await writeJson('src/content/policies/learning-prerequisites.json', prerequisites);
  await writeJson(indexPath, {
    tags: catalog.tags,
    learningOutcomes: catalog.learningOutcomes,
    learningUnits: catalog.learningUnits,
    placements: policy.placements,
    learningPrerequisites: prerequisites,
  });
  await writeJson('src/content/problem-metrics/atcoder-problems.json', {
    schemaVersion: '1.0.0',
    provider: 'atcoder-problems',
    checkedAt: '2026-07-17T03:00:00+09:00',
    sources: ATCODER_PROBLEMS_SOURCES,
    problems: {
      [authoring.problemId]: {
        officialTaskId: 'abc212_e',
        difficulty: null,
        difficultyExperimental: null,
        point: null,
      },
    },
  });
  await writeText(
    'src/lib/taxonomy/textbook-order.ts',
    "export const TEXTBOOK_CHAPTERS = [{ id: 'unit-graphs', unitIds: [] }];\n",
  );
  const constitution = '**Version**: 3.0.0\n';
  await writeText('.specify/memory/constitution.md', constitution);
  const templatePath = '.specify/templates/plan-template.md';
  const template = 'Fixture plan template.\n';
  await writeText(templatePath, template);
  const contentFiles = await releaseContentInventory(repositoryRoot);
  const subjectDigest = canonicalDigest(contentFiles);
  const checkPath = 'docs/verification/check-catalog.json';
  const check = {
    schemaVersion: '1.0.0',
    checkId: 'check-catalog',
    command: 'npm run test:contract',
    subjectDigest,
    exitCode: 0,
    passed: true,
    completedAt: '2026-07-17T12:00:00+09:00',
  };
  const checkDigest = await writeJson(checkPath, check);
  const applicableChecks = [
    {
      checkId: check.checkId,
      command: check.command,
      subjectDigest: check.subjectDigest,
      exitCode: check.exitCode,
      passed: check.passed,
      completedAt: check.completedAt,
      resultPath: checkPath,
      resultDigest: checkDigest,
      executedByReviewerId: 'person-author',
    },
  ];
  const reviewPath = 'docs/reviews/human-content/review-catalog.json';
  const review: Record<string, unknown> = {
    schemaVersion: '3.0.0',
    id: 'human-content-review-catalog',
    scopeType: 'release',
    scopeId: 'release-2026-07-17',
    releaseVersion: '2026.07.17',
    subjectDigest,
    inventoryPath: 'docs/verification/review-inventory.json',
    inventoryDigest: '',
    reviewPolicy: { requiredMode: 'self', riskReasons: [] } as const,
    reviewMode: 'self',
    applicableChecks,
    applicableCheckCount: 1,
    passedApplicableCheckCount: 1,
    reviewerExecutedCheckSetDigest: canonicalDigest(applicableChecks),
    authors: [{ personId: 'person-author', authoredItemIds: ['human-review-item-catalog'] }],
    reviewer: { personId: 'person-author', mode: 'self' },
    reviewItems: [
      {
        reviewItemId: 'human-review-item-catalog',
        kind: 'non_automatable_claim',
        subjectPaths: ['src/content/docs/index.md'],
        authorIds: ['person-author'],
        learningOutcomeIds: [],
        reviewerId: 'person-author',
        reviewBasis: 'Compared the claim with its source.',
        decision: 'approved',
        findings: [],
        reviewedAt: '2026-07-17T12:30:00+09:00',
      },
    ],
    inventoryItemCount: 1,
    reviewedItemCount: 1,
    approvedItemCount: 1,
    changesRequestedItemCount: 0,
    unreviewedItemCount: 0,
    outcomeCoverageReview: {
      reviewerId: 'person-author',
      authorIds: ['person-author'],
      decision: 'no_outcome_impact_confirmed',
      learningOutcomeIds: [],
      subjectPaths: ['src/content/docs/index.md'],
      rationale: 'The content does not change an observable learning outcome.',
      noOutcomeImpactRationale: 'No learning outcome changes.',
      confirmedAt: '2026-07-17T12:30:00+09:00',
    },
    outcomeCoverageConfirmed: true,
    aggregatePassed: true,
    generatedAt: '2026-07-17T12:31:00+09:00',
    evidenceDigest: '',
  };
  const manifestScope = {
    taskId: 'T024',
    requiredRequirementIds: ['FR-026'],
    learningOutcomeIds: [],
    reviewPolicy: { requiredMode: 'self', riskReasons: [] } as const,
    reviewUnits: [
      {
        reviewUnitId: 'RU-T024-catalog',
        changeKind: 'documentation',
        paths: ['src/content/docs/index.md'],
        itemIds: ['human-review-item-catalog'],
        requirementIds: ['FR-026'],
        learningOutcomeIds: [],
        outcomeImpact: { kind: 'none', rationale: 'No learner outcome changes.' },
        dependencyReviewUnitIds: [],
        checkIds: [check.checkId],
        evidenceRoles: ['non_automatable_claim'],
        maintenanceBenefit: null,
        owner: 'person-author',
        status: 'complete',
      },
    ],
  };
  const workManifest: Record<string, unknown> = {
    schemaVersion: '2.0.0',
    manifestId: 'work-manifest-T024-catalog',
    ...manifestScope,
    scopeDigest: calculateContentWorkManifestScopeDigest(manifestScope),
    digest: '',
    changeKind: 'documentation',
    outcomeImpact: { kind: 'none', rationale: 'No learner outcome changes.' },
    maintenanceBenefit: null,
    state: 'complete',
    createdAt: '2026-07-17T10:00:00+09:00',
    updatedAt: '2026-07-17T11:00:00+09:00',
  };
  workManifest.digest = digestWithoutField(workManifest, 'digest');

  const manifestPath = 'docs/work-manifests/catalog/manifest.json';
  await writeJson(manifestPath, workManifest);
  const sealRelease = async () => {
    const subjectFiles = await releaseContentInventory(repositoryRoot);
    const subjectDigest = canonicalDigest(subjectFiles);
    catalog.release.manifestDigest = String(workManifest.digest);
    catalog.release.contentFileInventoryDigest = subjectDigest;
    catalog.release.contentSnapshotDigest = catalogContentDigest(catalog);
    check.subjectDigest = subjectDigest;
    const checkDigest = await writeJson(checkPath, check);
    const reference = {
      checkId: check.checkId,
      command: check.command,
      subjectDigest,
      resultPath: checkPath,
      resultDigest: checkDigest,
      exitCode: 0,
      passed: true,
      completedAt: check.completedAt,
    };
    catalog.release.validationSummary = {
      checkCount: 1,
      passedCheckCount: 1,
      blockingFindingCount: 0,
      evidenceDigests: [checkDigest],
      checks: [reference],
    };
    const reviewChecks = [{ ...reference, executedByReviewerId: 'person-author' }];
    review.subjectDigest = subjectDigest;
    review.releaseVersion = catalog.release.version;
    review.applicableChecks = reviewChecks;
    review.reviewerExecutedCheckSetDigest = canonicalDigest(reviewChecks);
    review.inventoryDigest = deriveCatalogEvidenceTrustContext({
      catalog,
      workManifest,
    }).inventoryDigest;
    review.evidenceDigest = digestWithoutField(review, 'evidenceDigest');
    const reviewDigest = await writeJson(reviewPath, review);
    const reviewRef = {
      evidenceId: String(review.id),
      path: reviewPath,
      digest: reviewDigest,
      subjectDigest,
      authorIds: ['person-author'],
      reviewerIds: ['person-author'],
      reviewMode: 'self' as const,
      aggregatePassed: true as const,
    };
    catalog.release.humanContentReviewEvidenceRefs = [reviewRef];
    await writeJson(FULL_RELEASE_EVIDENCE_PATH, {
      subjectDigest,
      checks: [reference],
      reviews: [reviewRef],
    });
    const rawPath = 'docs/verification/check-raw.txt';
    const rawDigest = await writeText(rawPath, 'Fixture check passed.\n');
    const merge = {
      schemaVersion: '3.0.0',
      id: 'merge-review-catalog',
      changeId: 'change-catalog',
      logicalChangeSubjectDigest: subjectDigest,
      subjectFiles,
      excludedArtifacts: [],
      workManifestPath: manifestPath,
      workManifestDigest: workManifest.digest,
      learningOutcomeIds: [],
      outcomeImpact: { kind: 'none', rationale: 'No outcome changes in this fixture.' },
      reviewMode: 'self',
      reviewerId: 'person-author',
      applicableChecks: [
        {
          checkId: check.checkId,
          command: check.command,
          subjectDigest,
          resultPath: checkPath,
          resultDigest: checkDigest,
          exitCode: 0,
          completedAt: check.completedAt,
          executedByReviewerId: 'person-author',
          rawResultPath: rawPath,
          rawResultDigest: rawDigest,
        },
      ],
      notApplicableChecks: [],
      humanContentReviewEvidenceId: review.id,
      humanContentReviewEvidencePath: reviewPath,
      humanContentReviewEvidenceDigest: reviewDigest,
      constitutionCheck: {
        constitutionPath: '.specify/memory/constitution.md',
        constitutionVersion: '3.0.0',
        constitutionDigest: fileDigest(constitution),
        dependentTemplates: [
          {
            path: templatePath,
            sha256: fileDigest(template),
            byteLength: Buffer.byteLength(template),
          },
        ],
        violationCount: 0,
        passed: true,
        checkedAt: check.completedAt,
      },
      unresolvedBlockingFindingCount: 0,
      mergeApproved: true,
      reviewedAt: '2026-07-17T12:30:00+09:00',
      evidenceDigest: '',
    };
    merge.evidenceDigest = digestWithoutField(merge, 'evidenceDigest');
    await writeJson(FULL_RELEASE_MERGE_REVIEW_PATH, merge);
    await writeJson(FULL_RELEASE_CATALOG_PATH, catalog);
  };
  // The base is a real, schema-valid published release with mutually bound bytes.
  await sealRelease();
  return { catalog, authoring, writeAuthoring, sealRelease, writeJson };
};
