/**
 * Source-backed primary Tag proposals for ABC 384--466 (E/F/G).
 *
 * Each value is the first reusable abstraction that commits the adopted
 * approach. Technique names are used only as confirmation; generic root Tags
 * and merely supporting implementation structures are intentionally omitted.
 */
export const CURATED_PRIMARY_TAG_ASSIGNMENTS_384_466 = {
  'abc384-e': 'tag-ordered-set-heap',
  'abc384-f': 'tag-prime-divisor-decomposition',
  'abc384-g': 'tag-mo-offline-range',
  'abc385-e': 'tag-greedy-exchange-order',
  'abc385-f': 'tag-geometry-orientation-transform',
  'abc385-g': 'tag-convolution-fps',
  'abc386-e': 'tag-bounded-enumeration',
  'abc386-f': 'tag-edit-distance-dp',
  // Connected labeled-graph counting provides the expensive per-threshold computation.
  'abc386-g': 'tag-labeled-component-decomposition',
  'abc387-e': 'tag-constructive-witness',
  'abc387-f': 'tag-functional-graph-doubling',
  'abc387-g': 'tag-convolution-fps',
  'abc388-e': 'tag-greedy-exchange-order',
  // The Frobenius-style eventual-reachability bound makes boundary compression finite.
  'abc388-f': 'tag-gcd-diophantine',
  'abc388-g': 'tag-monotone-threshold-search',
  'abc389-e': 'tag-discrete-convex-marginal',
  'abc389-f': 'tag-lazy-segment-action',
  // BFS layers describe a counted object; this is not a reachability search.
  'abc389-g': 'tag-dp-state-equivalence',
  'abc390-e': 'tag-knapsack-resource',
  'abc390-f': 'tag-contribution-reordering',
  'abc390-g': 'tag-convolution-fps',
  'abc391-e': 'tag-tree-aggregation-reroot',
  'abc391-f': 'tag-ordered-set-heap',
  // The bit mask is a canonical LCS frontier, not a subset-selection state.
  'abc391-g': 'tag-dp-state-equivalence',
  'abc392-e': 'tag-dsu-connectivity',
  'abc392-f': 'tag-reverse-offline',
  'abc392-g': 'tag-convolution-fps',
  'abc393-e': 'tag-prime-divisor-decomposition',
  'abc393-f': 'tag-sequence-subsequence-dp',
  'abc393-g': 'tag-flow-matching-cut',
  'abc394-e': 'tag-reachability-bfs',
  'abc394-f': 'tag-tree-aggregation-reroot',
  'abc394-g': 'tag-dsu-connectivity',
  'abc395-e': 'tag-shortest-path',
  'abc395-f': 'tag-monotone-threshold-search',
  'abc395-g': 'tag-subset-bitmask-transform',
  'abc396-e': 'tag-linear-algebra-xor',
  'abc396-f': 'tag-contribution-reordering',
  'abc396-g': 'tag-subset-bitmask-transform',
  // Leaf-side path remnants are combined by a postorder tree DP.
  'abc397-e': 'tag-tree-aggregation-reroot',
  'abc397-f': 'tag-lazy-segment-action',
  'abc397-g': 'tag-flow-matching-cut',
  'abc398-e': 'tag-game-parity-invariant',
  'abc398-f': 'tag-palindrome-radius',
  'abc398-g': 'tag-game-parity-invariant',
  'abc399-e': 'tag-functional-graph-doubling',
  'abc399-f': 'tag-combinatorial-coefficients',
  'abc399-g': 'tag-linear-algebra-xor',
  'abc400-e': 'tag-prime-divisor-decomposition',
  'abc400-f': 'tag-interval-partition-dp',
  'abc400-g': 'tag-discrete-convex-marginal',
  'abc401-e': 'tag-dsu-connectivity',
  'abc401-f': 'tag-tree-metric-diameter',
  'abc401-g': 'tag-flow-matching-cut',
  'abc402-e': 'tag-stochastic-expectation-dp',
  'abc402-f': 'tag-divide-enumerate',
  'abc402-g': 'tag-integer-boundary-blocks',
  // Trie membership is cheap; the decisive bound is one-time invalidation.
  'abc403-e': 'tag-amortized-heavy-light',
  // Syntax category, rather than numeric value alone, is the sufficient state.
  'abc403-f': 'tag-dp-state-equivalence',
  'abc403-g': 'tag-monoid-segment-tree',
  'abc404-e': 'tag-greedy-exchange-order',
  'abc404-f': 'tag-stochastic-expectation-dp',
  // Prefix sums encode constraints, but Bellman--Ford solves their feasibility.
  'abc404-g': 'tag-shortest-path',
  'abc405-e': 'tag-combinatorial-coefficients',
  'abc405-f': 'tag-laminar-interval-containment-tree',
  'abc405-g': 'tag-mo-offline-range',
  'abc406-e': 'tag-digit-dp',
  'abc406-f': 'tag-tree-path-decomposition',
  'abc406-g': 'tag-discrete-convex-marginal',
  'abc407-e': 'tag-greedy-exchange-order',
  'abc407-f': 'tag-contribution-reordering',
  'abc407-g': 'tag-flow-matching-cut',
  // Bitwise feasibility is certified by connectivity, not by exchange order.
  'abc408-e': 'tag-dsu-connectivity',
  'abc408-f': 'tag-dp-transition-acceleration',
  'abc408-g': 'tag-gcd-diophantine',
  'abc409-e': 'tag-tree-aggregation-reroot',
  'abc409-f': 'tag-ordered-set-heap',
  'abc409-g': 'tag-convolution-fps',
  'abc410-e': 'tag-knapsack-resource',
  'abc410-f': 'tag-prefix-difference',
  'abc410-g': 'tag-sequence-subsequence-dp',
  'abc411-e': 'tag-contribution-reordering',
  'abc411-f': 'tag-amortized-heavy-light',
  'abc411-g': 'tag-subset-bitmask-transform',
  'abc412-e': 'tag-prime-divisor-decomposition',
  'abc412-f': 'tag-stochastic-expectation-dp',
  'abc412-g': 'tag-flow-matching-cut',
  'abc413-e': 'tag-divide-enumerate',
  'abc413-f': 'tag-game-value-dp',
  // Planar duality turns the obstacle question into sparse dual connectivity.
  'abc413-g': 'tag-planar-duality',
  'abc414-e': 'tag-integer-boundary-blocks',
  'abc414-f': 'tag-reachability-bfs',
  // The segment-tree graph is an edge compressor for an ordinary shortest path.
  'abc414-g': 'tag-shortest-path',
  'abc415-e': 'tag-grid-table-dp',
  'abc415-f': 'tag-monoid-segment-tree',
  'abc415-g': 'tag-knapsack-resource',
  'abc416-e': 'tag-shortest-path',
  // Path count and endpoint status are composed over rooted subtrees.
  'abc416-f': 'tag-tree-aggregation-reroot',
  'abc416-g': 'tag-dp-state-equivalence',
  'abc417-e': 'tag-greedy-exchange-order',
  'abc417-f': 'tag-lazy-segment-action',
  // HLD only accelerates navigation in the already compressed concat DAG.
  'abc417-g': 'tag-recursive-compressed-string',
  'abc418-e': 'tag-contribution-reordering',
  'abc418-f': 'tag-monoid-segment-tree',
  // Myhill--Nerode signatures are used to construct the finite transition automaton itself.
  'abc418-g': 'tag-string-automata',
  'abc419-e': 'tag-knapsack-resource',
  'abc419-f': 'tag-string-automata',
  'abc419-g': 'tag-graph-core-peeling',
  'abc420-e': 'tag-dsu-connectivity',
  'abc420-f': 'tag-cartesian-tree',
  'abc420-g': 'tag-prime-divisor-decomposition',
  'abc421-e': 'tag-stochastic-expectation-dp',
  // The reusable abstraction is the ID-indexed linked list; amortization bounds the splice walk.
  'abc421-f': 'tag-linked-list-index',
  'abc421-g': 'tag-flow-matching-cut',
  'abc422-e': 'tag-randomized-algorithm',
  'abc422-f': 'tag-dp-state-equivalence',
  'abc422-g': 'tag-convolution-fps',
  'abc423-e': 'tag-contribution-reordering',
  'abc423-f': 'tag-inclusion-exclusion',
  'abc423-g': 'tag-modular-crt',
  'abc424-e': 'tag-monotone-threshold-search',
  'abc424-f': 'tag-monoid-segment-tree',
  'abc424-g': 'tag-knapsack-resource',
  'abc425-e': 'tag-combinatorial-coefficients',
  'abc425-f': 'tag-subset-bitmask-transform',
  'abc425-g': 'tag-binary-trie',
  'abc426-e': 'tag-geometry-orientation-transform',
  'abc426-f': 'tag-lazy-segment-action',
  'abc426-g': 'tag-divide-enumerate',
  'abc427-e': 'tag-reachability-bfs',
  'abc427-f': 'tag-divide-enumerate',
  // Equal transition functions are merged into a composable normal form.
  'abc427-g': 'tag-symmetry-invariant-normalization',
  'abc428-e': 'tag-tree-metric-diameter',
  'abc428-f': 'tag-amortized-heavy-light',
  // Burnside counts rotation orbits after quotienting by cyclic symmetry.
  'abc428-g': 'tag-symmetry-invariant-normalization',
  'abc429-e': 'tag-reachability-bfs',
  'abc429-f': 'tag-monoid-segment-tree',
  'abc429-g': 'tag-integer-boundary-blocks',
  'abc430-e': 'tag-prefix-matching-automata',
  'abc430-f': 'tag-prefix-difference',
  'abc430-g': 'tag-lazy-segment-action',
  'abc431-e': 'tag-shortest-path',
  'abc431-f': 'tag-combinatorial-coefficients',
  'abc431-g': 'tag-ordered-set-heap',
  'abc432-e': 'tag-monoid-segment-tree',
  'abc432-f': 'tag-subset-bitmask-transform',
  'abc432-g': 'tag-convolution-fps',
  'abc433-e': 'tag-greedy-exchange-order',
  // Vandermonde removes the apparent sequence DP entirely.
  'abc433-f': 'tag-combinatorial-coefficients',
  // Building the suffix automaton creates the linear-size game graph; retrograde play follows.
  'abc433-g': 'tag-string-automata',
  'abc434-e': 'tag-dsu-connectivity',
  'abc434-f': 'tag-greedy-exchange-order',
  'abc434-g': 'tag-monoid-segment-tree',
  'abc435-e': 'tag-ordered-set-heap',
  'abc435-f': 'tag-cartesian-tree',
  'abc435-g': 'tag-lazy-segment-action',
  'abc436-e': 'tag-functional-graph-doubling',
  'abc436-f': 'tag-contribution-reordering',
  'abc436-g': 'tag-convolution-fps',
  // The Trie is used as the canonical prefix-state representation for ordering.
  'abc437-e': 'tag-trie-prefix',
  'abc437-f': 'tag-geometry-orientation-transform',
  'abc437-g': 'tag-flow-matching-cut',
  'abc438-e': 'tag-functional-graph-doubling',
  'abc438-f': 'tag-contribution-reordering',
  'abc438-g': 'tag-gcd-diophantine',
  'abc439-e': 'tag-sequence-subsequence-dp',
  'abc439-f': 'tag-contribution-reordering',
  'abc439-g': 'tag-convolution-fps',
  'abc440-e': 'tag-ordered-set-heap',
  'abc440-f': 'tag-monoid-segment-tree',
  // Component contraction is preparatory; the reusable core is the sufficient layered state.
  'abc440-g': 'tag-dp-state-equivalence',
  'abc441-e': 'tag-prefix-difference',
  'abc441-f': 'tag-knapsack-resource',
  'abc441-g': 'tag-lazy-segment-action',
  'abc442-e': 'tag-geometry-orientation-transform',
  'abc442-f': 'tag-dp-transition-acceleration',
  'abc442-g': 'tag-bounded-enumeration',
  'abc443-e': 'tag-grid-table-dp',
  'abc443-f': 'tag-reachability-bfs',
  'abc443-g': 'tag-integer-boundary-blocks',
  'abc444-e': 'tag-two-pointers-window',
  'abc444-f': 'tag-monotone-threshold-search',
  'abc444-g': 'tag-prime-divisor-decomposition',
  'abc445-e': 'tag-prime-divisor-decomposition',
  'abc445-f': 'tag-linear-recurrence-matrix',
  'abc445-g': 'tag-flow-matching-cut',
  // The decisive operation is reverse reachability from all zero states.
  'abc446-e': 'tag-reachability-bfs',
  'abc446-f': 'tag-reachability-bfs',
  // A unique lexicographically minimal index sequence canonicalizes every value sequence.
  'abc446-g': 'tag-symmetry-invariant-normalization',
  'abc447-e': 'tag-greedy-exchange-order',
  'abc447-f': 'tag-tree-aggregation-reroot',
  'abc447-g': 'tag-monoid-segment-tree',
  // This is concatenation-monoid doubling, not a functional-graph jump.
  'abc448-e': 'tag-linear-recurrence-matrix',
  'abc448-f': 'tag-constructive-witness',
  'abc448-g': 'tag-convex-hull-trick',
  'abc449-e': 'tag-event-sweep',
  'abc449-f': 'tag-event-sweep',
  'abc449-g': 'tag-convolution-fps',
  'abc450-e': 'tag-recursive-compressed-string',
  // Reachable-prefix maximum is the sufficient state; the lazy tree only batches transitions.
  'abc450-f': 'tag-dp-state-equivalence',
  // Exchange symmetry supplies a scalar expectation recurrence.
  'abc450-g': 'tag-stochastic-expectation-dp',
  'abc451-e': 'tag-additive-tree-metric-reconstruction',
  'abc451-f': 'tag-bipartite-structure',
  'abc451-g': 'tag-xor-linear-basis',
  'abc452-e': 'tag-integer-boundary-blocks',
  'abc452-f': 'tag-two-pointers-window',
  // RLE is preparatory; distinctness is decided by suffix order and LCP.
  'abc452-g': 'tag-suffix-lcp-index',
  'abc453-e': 'tag-event-sweep',
  'abc453-f': 'tag-constructive-witness',
  'abc453-g': 'tag-persistent-rollback',
  'abc454-e': 'tag-constructive-witness',
  'abc454-f': 'tag-prefix-difference',
  // "DSU on Tree" here is the small-to-large amortization pattern, not connectivity.
  'abc454-g': 'tag-amortized-heavy-light',
  'abc455-e': 'tag-inclusion-exclusion',
  'abc455-f': 'tag-lazy-segment-action',
  // Equality of randomized prefix fingerprints is the decisive query primitive.
  'abc455-g': 'tag-string-hash-equality',
  'abc456-e': 'tag-directed-condensation-toposort',
  'abc456-f': 'tag-swag',
  'abc456-g': 'tag-inclusion-exclusion',
  // Endpoint-extreme intervals dominate every other possible two-cover witness.
  'abc457-e': 'tag-greedy-exchange-order',
  'abc457-f': 'tag-dp-transition-acceleration',
  // The coordinate transform exposes an order, but LDS/patience sorting solves the path cover.
  'abc457-g': 'tag-sequence-subsequence-dp',
  'abc458-e': 'tag-combinatorial-coefficients',
  'abc458-f': 'tag-string-automata',
  'abc458-g': 'tag-monotone-threshold-search',
  'abc459-e': 'tag-tree-aggregation-reroot',
  'abc459-f': 'tag-monotone-stack-queue',
  'abc459-g': 'tag-two-variable-convex-lattice-optimization',
  'abc460-e': 'tag-modular-crt',
  'abc460-f': 'tag-monoid-segment-tree',
  'abc460-g': 'tag-static-top-tree',
  'abc461-e': 'tag-fenwick-weighted-prefix',
  'abc461-f': 'tag-knapsack-resource',
  'abc461-g': 'tag-flow-matching-cut',
  'abc462-e': 'tag-symmetry-invariant-normalization',
  'abc462-f': 'tag-dp-state-equivalence',
  // Class-wise inclusion--exclusion creates the factors later multiplied by NTT.
  'abc462-g': 'tag-inclusion-exclusion',
  'abc463-e': 'tag-shortest-path',
  'abc463-f': 'tag-symmetry-invariant-normalization',
  // Mo ordering accelerates queries only after reduction to binomial prefix moments.
  'abc463-g': 'tag-combinatorial-coefficients',
  // Last-write timestamps turn all rectangle overwrites into one offline suffix maximum.
  'abc464-e': 'tag-reverse-offline',
  'abc464-f': 'tag-divide-enumerate',
  'abc464-g': 'tag-ordered-set-heap',
  'abc465-e': 'tag-digit-dp',
  'abc465-f': 'tag-prefix-difference',
  'abc465-g': 'tag-ordered-set-heap',
  'abc466-e': 'tag-interval-partition-dp',
  'abc466-f': 'tag-amortized-monotone-progress',
  // The carry-vector DP counts assignments after weighted DSU extracts independent constraints.
  'abc466-g': 'tag-carry-mixed-radix-dp',
} as const satisfies Readonly<Record<string, string>>;
