export const FINAL_TAG_LEARNER_ALIASES: Readonly<Record<string, readonly string[]>> = {
  'tag-amortized-heavy-light': [
    '償却解析',
    '平方根分割',
    'amortized analysis',
    'sqrt decomposition',
  ],
  'tag-bounded-enumeration': [
    '制約を利用した全探索',
    '小さい候補集合の全列挙',
    'bounded exhaustive search',
    'finite case enumeration',
  ],
  'tag-bipartite-structure': ['二部グラフ', '二部彩色', 'bipartite graph', '2-coloring'],
  'tag-binary-trie': ['01-Trie', 'bitwise trie', 'XOR Trie'],
  'tag-bitset-word-parallel': ['ビット集合', 'word-parallel algorithm', 'bitset optimization'],
  'tag-cartesian-tree': ['デカルト木', 'Cartesian tree', 'min Cartesian tree'],
  'tag-carry-mixed-radix-dp': ['繰り上がりDP', '混合基数DP', 'carry DP', 'mixed-radix DP'],
  'tag-combinatorial-coefficients': ['二項係数', '重複組合せ', 'binomial coefficients'],
  'tag-constructive-witness': ['構築問題', 'constructive algorithms'],
  'tag-coordinate-compression': [
    '座標圧縮',
    '値圧縮',
    'coordinate compression',
    'rank compression',
  ],
  'tag-contribution-reordering': ['主客転倒', 'contribution technique'],
  'tag-convex-hull-halfplane': [
    '凸幾何',
    '半平面交差',
    'convex geometry',
    'half-plane intersection',
  ],
  'tag-convex-hull-trick': ['Convex Hull Trick', 'CHT', '直線包絡'],
  'tag-convolution-fps': [
    '形式的冪級数',
    'formal power series',
    '多項式畳み込み',
    'multipoint evaluation',
    'NTT',
    'FFT',
  ],
  'tag-cyclic-group-order': ['乗法的位数', 'multiplicative order', 'primitive root'],
  'tag-determinant-counting': [
    '行列式による数え上げ',
    '行列木定理',
    'Matrix-Tree theorem',
    'LGV lemma',
  ],
  'tag-digit-dp': ['桁DP', 'digit DP', 'tight DP', '上限制約付き桁DP'],
  'tag-directed-condensation-toposort': [
    '強連結成分分解',
    'SCC',
    'トポロジカルソート',
    'topological sort',
    '2-SAT',
    '含意グラフ',
    'implication graph',
  ],
  'tag-discrete-convex-marginal': ['スロープトリック', 'Slope Trick', 'convex cost'],
  'tag-divide-enumerate': [
    '半分全列挙',
    'meet-in-the-middle',
    'MITM',
    '分割統治',
    'divide and conquer',
  ],
  'tag-dp-state-equivalence': ['状態圧縮DP', 'state-compressed DP', 'minimal sufficient state'],
  'tag-dp-state-transition': ['動的計画法', 'dynamic programming', 'DP'],
  'tag-dp-transition-acceleration': ['DP高速化', 'DP optimization'],
  'tag-dsu-connectivity': [
    'Union-Find',
    '素集合データ構造',
    'disjoint set union',
    '連結成分縮約',
    'component contraction',
  ],
  'tag-euler-degree-parity': ['オイラー路', '一筆書き', 'Eulerian trail'],
  'tag-fenwick-weighted-prefix': ['フェニック木', 'Binary Indexed Tree', 'BIT'],
  'tag-finite-field-extension': [
    '有限体拡大',
    'extension field',
    'quadratic finite field',
    'Nim product',
  ],
  'tag-flow-matching-cut': ['最大流', '最小カット', '二部マッチング', 'max flow'],
  'tag-functional-graph-doubling': ['写像のダブリング', 'functional graph', 'binary lifting'],
  'tag-game-grundy-dp': ['ゲームDP', '組合せゲーム', 'combinatorial game DP', 'Nim'],
  'tag-game-value-dp': ['minimax', 'ミニマックス', '得点差ゲームDP', 'partisan game'],
  'tag-grid-table-dp': ['グリッドDP', '二次元DP', 'grid DP', 'table DP'],
  'tag-gcd-diophantine': [
    '最大公約数',
    'ユークリッドの互除法',
    'Euclidean algorithm',
    'Diophantine equation',
    '数値半群',
    'Frobeniusの硬貨問題',
    'numerical semigroup',
    'Frobenius coin problem',
    'conductor',
  ],
  'tag-geometry-orientation-transform': [
    '計算幾何',
    '外積判定',
    'computational geometry',
    'Manhattan transform',
  ],
  'tag-graph-core-peeling': ['2-core', '葉刈り', 'graph peeling'],
  'tag-graph-model-structure': ['グラフ理論', 'graph algorithms'],
  'tag-greedy-exchange-order': ['貪欲法', '交換法', 'greedy algorithm'],
  'tag-inclusion-exclusion': ['包除原理', 'inclusion-exclusion principle'],
  'tag-integer-boundary-blocks': ['商が一定の区間', '整数平方根', 'floor quotient grouping'],
  'tag-implicit-binary-tree-arithmetic': [
    '暗黙の完全二分木',
    '完全二分木の深さ集約',
    'heap index tree',
    'implicit complete binary tree',
    'symmetric complete binary tree',
  ],
  'tag-interactive-protocol': [
    'インタラクティブ問題',
    '対話型問題',
    'interactive problem',
    'query protocol',
  ],
  'tag-interval-partition-dp': ['区間DP', '分割DP', 'interval DP'],
  'tag-knapsack-resource': ['ナップサックDP', '部分和DP', 'knapsack DP'],
  'tag-lazy-segment-action': ['遅延セグメント木', 'lazy segment tree', 'lazy propagation'],
  'tag-linear-algebra-xor': [
    'ガウス消去法',
    '線形基底',
    'Gaussian elimination',
    'XOR basis',
    'Kronecker積',
    'tensor-product transform',
  ],
  'tag-linear-recurrence-matrix': ['行列累乗', 'matrix exponentiation'],
  'tag-linked-list-index': ['連結リスト', 'linked list', 'doubly linked list'],
  'tag-lowlink-critical-structure': ['Low-Link', '橋・関節点', 'bridges and articulation points'],
  'tag-math-geometry-transformation': ['数学的帰着', '数式化', 'mathematical reduction'],
  'tag-mo-offline-range': ['Mo法', 'ムーのアルゴリズム', "Mo's algorithm"],
  'tag-model-reduction': ['問題の言い換え', 'modeling', 'problem reduction'],
  'tag-modular-arithmetic': [
    '法上の四則演算',
    'モジュラ逆元',
    '零を含む動的積',
    'modular arithmetic',
    'modular inverse',
    'modular exponentiation',
    'zero-aware modular product',
  ],
  'tag-modular-crt': ['一次合同式', '中国剰余定理', 'Chinese remainder theorem', 'CRT'],
  'tag-monoid-segment-tree': [
    'セグメント木',
    '線分木',
    'segment tree',
    'canonical区間分解',
    'segment tree canonical cover',
    'segment tree graph',
    '時間セグメント木',
  ],
  'tag-monotone-stack-queue': ['単調スタック', '単調キュー', 'monotonic stack', 'monotonic queue'],
  'tag-monotone-threshold-search': ['答えの二分探索', '二分探索', 'binary search on the answer'],
  'tag-ordered-set-heap': ['優先度付きキュー', '平衡二分探索木', 'priority queue', 'ordered set'],
  'tag-palindrome-radius': ['Manacher法', "Manacher's algorithm"],
  'tag-persistent-rollback': [
    '永続データ構造',
    'ロールバック',
    'persistent data structure',
    'rollback',
  ],
  'tag-prefix-difference': ['いもす法', '累積和', 'prefix sums', 'difference array'],
  'tag-prefix-matching-automata': ['KMP法', 'Zアルゴリズム', 'prefix function'],
  'tag-prime-divisor-decomposition': ['素因数分解', '約数列挙', 'prime factorization', 'sieve'],
  'tag-query-sufficient-aggregate': ['動的区間集約', '更新可能な要約', 'dynamic range aggregate'],
  'tag-reachability-bfs': [
    '幅優先探索',
    '深さ優先探索',
    'breadth-first search',
    'BFS',
    'DFS',
    '推移閉包',
    'Warshall法',
  ],
  'tag-randomized-algorithm': [
    '乱択アルゴリズム',
    'Monte Carlo algorithm',
    'Las Vegas algorithm',
    'probabilistic method',
  ],
  'tag-recursive-compressed-string': ['圧縮文字列', 'compressed strings'],
  'tag-reverse-offline': ['逆順処理', 'クエリの逆読み', 'reverse offline processing'],
  'tag-sequence-subsequence-dp': ['部分列DP', '最長増加部分列', 'subsequence DP', 'LIS'],
  'tag-shortest-path': ['最短経路', 'Dijkstra法', 'Bellman–Ford法', 'shortest path'],
  'tag-shortest-path-certificate': [
    '最短路木',
    '経路復元',
    'shortest-path tree',
    'path reconstruction',
  ],
  'tag-spanning-tree-optimization': [
    '最小全域木',
    '最大全域木',
    'minimum spanning tree',
    'maximum spanning tree',
    'Kruskal法',
  ],
  'tag-static-top-tree': ['Top Tree', 'Static Top Tree', 'rake-compress tree'],
  'tag-stochastic-expectation-dp': [
    '期待値DP',
    '確率DP',
    'Markov DP',
    'stochastic dynamic programming',
  ],
  'tag-string-hash-equality': [
    'ローリングハッシュ',
    '文字列ハッシュ',
    'rolling hash',
    'string fingerprint',
  ],
  'tag-string-state-representation': ['文字列アルゴリズム', 'string algorithms'],
  'tag-string-automata': ['文字列オートマトン', 'Aho–Corasick', 'Suffix Automaton', 'SAM'],
  'tag-subset-bitmask-transform': ['部分集合DP', 'bit DP', 'bitmask DP', 'subset transform'],
  'tag-suffix-lcp-index': ['接尾辞配列', 'LCP配列', 'suffix array'],
  'tag-event-sweep': ['走査線', 'イベント走査', 'sweep line', 'event sweep'],
  'tag-symmetry-invariant-normalization': [
    '対称性の利用',
    '不変量',
    'canonicalization',
    'invariant',
    'Burnsideの補題',
    'Pólyaの数え上げ',
  ],
  'tag-tree-aggregation-reroot': ['木DP', '全方位木DP', 'tree DP', 'rerooting DP'],
  'tag-tree-balanced-separator': ['重心分解', 'centroid decomposition', 'tree separator'],
  'tag-tree-metric-diameter': [
    '木の直径',
    '木の中心',
    '最遠点',
    'tree diameter',
    'tree center',
    'eccentricity',
  ],
  'tag-tree-path-decomposition': [
    'HL分解',
    '最小共通祖先',
    'オイラーツアー',
    '仮想木',
    'heavy-light decomposition',
    'HLD',
    'LCA',
    'Euler tour',
    'virtual tree',
  ],
  'tag-trie-prefix': ['Trie', 'トライ木', 'prefix tree'],
  'tag-two-pointers-window': ['尺取り法', 'two pointers', 'sliding window'],
  'tag-witness-impact-localization': [
    '変更影響の局所化',
    'replacement paths',
    'witness-based sensitivity analysis',
  ],
  'tag-tree-model-structure': ['木アルゴリズム', 'tree algorithms'],
  'tag-number-theory-structure': ['数論', 'number theory'],
  'tag-combinatorics-algebra-structure': [
    '組合せ論・多項式・線形代数',
    'combinatorics and algebra',
  ],
  'tag-geometry-optimization-structure': ['幾何・凸最適化', 'geometry and convex optimization'],
  'tag-state-normalization': ['標準形による状態圧縮', 'state canonicalization'],
  'tag-group-action-orbit-counting': ['Burnsideの補題', 'Pólyaの数え上げ', 'orbit counting'],
  'tag-meet-in-the-middle': ['半分全列挙', 'meet-in-the-middle', 'MITM'],
  'tag-baby-step-giant-step': ['Baby-Step Giant-Step', 'BSGS', 'baby-step giant-step'],
  'tag-recursive-divide-and-conquer': ['分割統治', 'divide and conquer', 'CDQ分割統治'],
  'tag-amortized-monotone-progress': ['償却解析', 'amortized analysis', 'potential method'],
  'tag-small-to-large': ['small-to-large', 'DSU on Tree', 'sack technique'],
  'tag-threshold-heavy-light': ['平方根分割', '次数平方分割', 'sqrt decomposition'],
  'tag-heavy-path-tree-dp': ['HLRecDP', 'heavy-path tree DP'],
  'tag-subset-bitmask-dp': ['部分集合DP', 'bitmask DP', 'subset DP'],
  'tag-subset-zeta-mobius-transform': [
    '高速ゼータ変換',
    'subset zeta transform',
    'subset Möbius transform',
  ],
  'tag-subset-convolution': ['部分集合畳み込み', 'subset convolution'],
  'tag-directional-grid-effect-scan': [
    '方向別グリッド走査',
    '四方向scan',
    'directional grid scan',
    'ray sweep',
  ],
  'tag-state-graph-search': ['状態空間探索', '状態グラフ', 'implicit graph search'],
  'tag-transitive-closure': ['推移閉包', 'Warshall法', 'transitive closure'],
  'tag-scc-condensation': ['強連結成分分解', 'SCC', 'condensation DAG'],
  'tag-two-sat': ['2-SAT', '含意グラフ', 'implication graph'],
  'tag-functional-graph-decomposition': [
    '関数グラフ',
    'functional graph',
    'cycle-tree decomposition',
  ],
  'tag-binary-lifting': ['ダブリング', 'binary lifting', 'doubling'],
  'tag-dsu-components': ['DSU', 'Union-Find', 'disjoint set union', '素集合データ構造'],
  'tag-potential-dsu': ['重み付きUnion-Find', 'weighted Union-Find', 'potential DSU'],
  'tag-rooted-tree-aggregation': ['根付き木DP', 'tree DP', 'subtree DP'],
  'tag-periodic-tree-role-recovery': [
    '木上の距離剰余',
    '距離剰余labeling',
    'distance-residue labeling',
    'periodic tree role recovery',
  ],
  'tag-laminar-interval-containment-tree': [
    'laminar区間包含木',
    '区間包含木',
    'laminar family tree',
    'interval containment tree',
  ],
  'tag-rerooting': ['全方位木DP', 'rerooting DP', 'all-direction tree DP'],
  'tag-tree-ancestor-lca': ['最小共通祖先', 'LCA', 'ancestor query'],
  'tag-tree-euler-flattening': [
    'Euler Tourによる部分木区間化',
    'Euler tour flattening',
    'DFS order',
  ],
  'tag-heavy-light-decomposition': ['HL分解', 'Heavy-Light Decomposition', 'HLD'],
  'tag-virtual-tree': ['仮想木', 'virtual tree', 'auxiliary tree'],
  'tag-max-flow-min-cut': ['最大流', '最小カット', 'max flow', 'min cut'],
  'tag-flow-feasibility-lower-bounds': [
    '下限付きフロー',
    'lower-bound flow',
    'circulation with demands',
  ],
  'tag-bipartite-matching-hall': [
    '二部マッチング',
    'Hallの定理',
    'Kőnigの定理',
    'bipartite matching',
  ],
  'tag-min-cost-flow': ['最小費用流', 'min-cost flow', 'minimum-cost circulation'],
  'tag-weighted-bipartite-matching': [
    'ハンガリアン法',
    'assignment problem',
    'weighted bipartite matching',
  ],
  'tag-min-weight-general-perfect-matching': [
    '一般グラフ最小重み完全マッチング',
    'weighted blossom',
    'minimum-weight perfect matching',
  ],
  'tag-euler-trail-circuit': ['オイラー路', '一筆書き', 'Euler trail', 'Hierholzer法'],
  'tag-degree-parity-subgraph': ['次数偶奇部分グラフ', 'T-join', 'degree parity subgraph'],
  'tag-euler-circuit-counting': ['BEST定理', 'Euler circuit counting', 'BEST theorem'],
  'tag-near-tree-kernelization': ['near-tree kernelization', 'cycle-rank kernel', '次数2鎖圧縮'],
  'tag-range-monoid-aggregation': ['セグメント木', '線分木', 'segment tree', 'monoid range query'],
  'tag-segment-tree-canonical-decomposition': [
    'Segment Tree canonical cover',
    '時間セグメント木',
    'segment tree graph',
    'canonical区間分解',
  ],
  'tag-static-sorted-range-index': ['Merge Sort Tree', '静的range tree', 'merge sort tree'],
  'tag-idempotent-overlap-range-query': ['Sparse Table', '冪等RMQ', 'sparse table'],
  'tag-swag': ['SWAG', 'sliding window aggregation', 'two-stack queue'],
  'tag-finite-function-composition': [
    '有限写像の合成',
    'function monoid',
    'finite function composition',
  ],
  'tag-priority-queue-best-first': ['優先度付きキュー', 'heap', 'best-first enumeration'],
  'tag-ordered-set-multiset': [
    '平衡二分探索木',
    'ordered set',
    'multiset',
    'order statistics tree',
  ],
  'tag-ordered-interval-partition': ['ODT', '区間set', 'ordered disjoint tree'],
  'tag-prefix-interval-multiset-transform': [
    'prefix interval基底',
    'prefix interval multiset',
    'weighted prefix indicators',
    '剰余frequency圧縮',
  ],
  'tag-persistence': ['永続データ構造', 'persistent data structure', 'path copying'],
  'tag-rollback': ['ロールバックデータ構造', 'rollback DSU', 'undo stack'],
  'tag-z-algorithm-prefix-matching': ['Zアルゴリズム', 'Z algorithm', 'Z配列'],
  'tag-finite-pattern-automaton': ['有限オートマトン', 'DFA', 'finite-state automaton'],
  'tag-automaton-subset-construction': [
    'subset construction',
    'powerset construction',
    'NFAの決定化',
  ],
  'tag-aho-corasick': ['Aho–Corasick法', 'AC automaton', '多パターン照合'],
  'tag-automaton-dp': ['オートマトンDP', 'automaton DP', 'DFA DP'],
  'tag-suffix-automaton': ['Suffix Automaton', '接尾辞オートマトン', 'SAM'],
  'tag-sequence-fingerprint': ['ローリングハッシュ', 'rolling hash', 'polynomial hash'],
  'tag-randomized-algebraic-fingerprint': [
    'multiset hash',
    'Zobrist hash',
    'randomized algebraic fingerprint',
  ],
  'tag-modular-congruence-crt': ['中国剰余定理', 'CRT', '一次合同式', 'Chinese remainder theorem'],
  'tag-modular-periodicity': ['剰余周期', 'Fermatの小定理', 'Eulerの定理', 'modular periodicity'],
  'tag-bezout-diophantine': [
    'Bézout等式',
    '拡張Euclid',
    '一次不定方程式',
    'extended Euclidean algorithm',
  ],
  'tag-gcd-structure': ['gcd不変量', 'range gcd', '差分gcd'],
  'tag-numerical-semigroup': [
    '数値半群',
    'Frobeniusの硬貨問題',
    'numerical semigroup',
    'conductor',
  ],
  'tag-rational-approximation': [
    '連分数',
    'Stern–Brocot木',
    'continued fraction',
    'Farey sequence',
  ],
  'tag-cyclic-exponent-counting': [
    '巡回群の指数化',
    'cyclic-group counting',
    'primitive-root exponentization',
  ],
  'tag-multiplicative-order': ['乗法的位数', 'multiplicative order', 'repunits period'],
  'tag-finite-field-frobenius': ['Frobenius写像', 'Frobenius automorphism', 'finite-field orbit'],
  'tag-divisor-mobius-inversion': [
    '約数Möbius反転',
    'divisor zeta transform',
    'number-theoretic Möbius inversion',
  ],
  'tag-convolution': ['畳み込み', 'NTT', 'FFT', 'convolution'],
  'tag-generating-functions': ['生成関数', '母関数', 'generating function'],
  'tag-formal-power-series': ['形式的べき級数', 'FPS', 'formal power series', 'Newton iteration'],
  'tag-polynomial-multipoint-evaluation': [
    '多点評価',
    'multipoint evaluation',
    'product tree',
    'remainder tree',
  ],
  'tag-polynomial-taylor-shift': [
    '多項式Taylor shift',
    '多項式平行移動',
    'polynomial Taylor shift',
    'factorial convolution shift',
  ],
  'tag-fps-composition-power-projection': ['FPS合成', 'power projection', 'polynomial composition'],
  'tag-bostan-mori': ['Bostan–Mori', '有理生成関数の係数抽出'],
  'tag-relaxed-convolution': ['Relaxed Convolution', 'online convolution', 'CDQ convolution'],
  'tag-linear-system-rank': ['掃き出し法', 'Gaussian elimination', 'matrix rank'],
  'tag-xor-linear-basis': ['XOR線形基底', 'linear basis over F2', 'XOR basis'],
  'tag-separable-linear-transform': [
    'Walsh–Hadamard変換',
    'WHT',
    'XOR convolution',
    'Kronecker積変換',
  ],
  'tag-matroid-greedy': ['マトロイド貪欲法', 'matroid greedy', 'weighted matroid basis'],
  'tag-linear-matroid-intersection': [
    '線形マトロイド交差',
    'linear matroid intersection',
    'randomized intersection rank',
  ],
  'tag-rsk-young-tableaux': ['Robinson–Schensted対応', 'RSK correspondence', 'Young tableau'],
  'tag-deletion-contraction': ['削除・縮約', 'deletion-contraction', 'Tutte recurrence'],
  'tag-convex-boundary-hull': ['凸包', 'convex hull', 'support function'],
  'tag-half-plane-constraints': [
    '半平面制約',
    'half-plane constraints',
    'convex polygon containment',
  ],
  'tag-basic-convex-optimization': ['一次元凸最適化', 'ternary search', 'unimodal optimization'],
  'tag-slope-trick': ['Slope Trick', 'スロープトリック', 'piecewise-linear convex DP'],
  'tag-lagrangian-relaxation': ['ラグランジュ緩和', 'Aliens trick', 'Aliens DP'],
  'tag-monge-optimization': ['Monge最適化', 'SMAWK', 'monotone minima'],
  'tag-isotonic-regression-pav': ['単調回帰', 'PAV', 'pool-adjacent-violators'],
  'tag-separable-convex-marginals': [
    '限界費用貪欲',
    '限界利益選択',
    'marginal-cost greedy',
    'monotone marginal selection',
    'separable convex allocation',
  ],
  'tag-dag-topological-processing': ['トポロジカルソート', 'DAG DP', 'topological processing'],
  'tag-directed-core-peeling': [
    '有向cycle検出',
    'three-color DFS',
    '有向グラフの葉刈り',
    'sink peeling',
    'Kahn elimination',
  ],
  'tag-monotone-path-contraction': ['DSU jump', 'next-unprocessed pointer', '単調path圧縮'],
  'tag-dsu-merge-tree': ['DSU merge tree', 'Kruskal reconstruction tree', '統合木'],
  'tag-steiner-tree-dp': ['Steiner tree DP', 'Dreyfus–Wagner法', 'シュタイナー木DP'],
  'tag-dynamic-segment-tree': ['動的セグメント木', 'implicit segment tree', 'sparse segment tree'],
  'tag-segment-tree-beats': ['Segment Tree Beats', 'range chmin/chmax'],
  'tag-parallel-binary-search': [
    '並列二分探索',
    'parallel binary search',
    'simultaneous binary search',
    'batched monotone search',
  ],
  'tag-planar-duality': ['平面双対グラフ', 'planar duality', 'cut–path duality'],
  'tag-bitwise-greedy-feasibility': ['bitwise greedy', '上位bit貪欲', 'mask feasibility greedy'],
  'tag-string-periodicity': ['文字列周期', 'primitive word', 'minimal period'],
  'tag-run-length-dynamics': ['run-length dynamics', 'ランレングス状態', 'RLE state'],
  'tag-min25-sieve': ['Min_25 sieve', 'Lucy DP', 'multiplicative-function summatory sieve'],
  'tag-gaussian-integers-two-squares': ['Gaussian整数', '二平方和', 'sum of two squares'],
  'tag-prufer-code': ['Prüfer code', 'Prüfer sequence', '次数制約付きラベル木'],
  'tag-directed-walk-periodicity': ['有向グラフ周期', 'cycle-length gcd', 'directed graph period'],
  'tag-reflection-principle': ['鏡像法', 'reflection principle', 'André reflection method'],
  'tag-labeled-component-decomposition': [
    'ラベル付き連結成分分解',
    'exponential formula for labeled structures',
    'connected-component DP',
  ],
  'tag-fractional-parametric-search': [
    '比率二分探索',
    'fractional programming',
    'parametric search for ratio',
  ],
  'tag-information-theoretic-query-design': [
    '情報量下界',
    'query code design',
    'binary incidence code',
  ],
  'tag-cyclic-order-crossing': ['円環順序', 'chord crossing', '端点交互配置'],
  'tag-kinetic-order-maintenance': [
    'kinetic sorting',
    '交差イベント順序更新',
    'kinetic order maintenance',
  ],
  'tag-poset-dilworth-antichain': [
    'Dilworthの定理',
    '最大反鎖',
    'minimum chain cover',
    'Dilworth theorem',
  ],
  'tag-tree-precedence-contraction': [
    '01 on Tree',
    'tree precedence scheduling',
    'cluster contraction',
  ],
  'tag-frontier-profile-dp': ['frontier DP', 'profile DP', 'plug DP'],
  'tag-semiring-matrix-exponentiation': [
    '半環行列累乗',
    'min-plus matrix exponentiation',
    'max-min matrix exponentiation',
  ],
  'tag-monoid-exponentiation': [
    'monoid exponentiation',
    '連結演算ダブリング',
    'associative composition exponentiation',
  ],
  'tag-additive-tree-metric-reconstruction': [
    '加法的木距離',
    'additive tree metric',
    'distance-matrix tree reconstruction',
  ],
  'tag-graph-potential-propagation': [
    'グラフpotential',
    'graph potential propagation',
    'XOR potential graph',
    '静的差分等式制約',
  ],
  'tag-difference-constraints': [
    '差分制約',
    'difference constraints',
    '差の不等式',
    'constraint graph',
  ],
  'tag-kruskal-threshold-sweep': [
    'Kruskal順DSU sweep',
    '重み順Union-Find',
    'weight-sorted offline connectivity sweep',
    'minimax connectivity threshold',
  ],
  'tag-path-matching-contraction': [
    'path matching縮約',
    'path matching contraction',
    'minimum k-matching on a path',
  ],
  'tag-eventual-unbounded-knapsack': [
    '大容量unbounded knapsack',
    'eventual linearity knapsack',
    'best-density item',
  ],
  'tag-backtracking-search': ['バックトラック', 'backtracking', 'mark-and-unmark DFS'],
};

export const FINAL_TAG_FORMER_NAMES: Readonly<Record<string, readonly string[]>> = {
  'tag-amortized-heavy-light': [],
  'tag-bounded-enumeration': [],
  'tag-bipartite-structure': [],
  'tag-binary-trie': [],
  'tag-bitset-word-parallel': [],
  'tag-cartesian-tree': [],
  'tag-carry-mixed-radix-dp': [],
  'tag-combinatorial-coefficients': [],
  'tag-constructive-witness': [],
  'tag-coordinate-compression': [],
  'tag-contribution-reordering': [],
  'tag-convex-hull-halfplane': [],
  'tag-convex-hull-trick': [],
  'tag-convolution-fps': [],
  'tag-cyclic-group-order': [],
  'tag-determinant-counting': [],
  'tag-digit-dp': [],
  'tag-linear-matroid-intersection': [],
  'tag-min-weight-general-perfect-matching': [],
  'tag-directed-condensation-toposort': [],
  'tag-discrete-convex-marginal': [],
  'tag-divide-enumerate': [],
  'tag-dp-state-equivalence': ['同値性によるDP状態圧縮'],
  'tag-dp-state-transition': [],
  'tag-dp-transition-acceleration': [],
  'tag-dsu-connectivity': [],
  'tag-euler-degree-parity': [],
  'tag-fenwick-weighted-prefix': [],
  'tag-finite-field-extension': [],
  'tag-flow-matching-cut': [],
  'tag-functional-graph-doubling': [],
  'tag-game-grundy-dp': [],
  'tag-game-value-dp': [],
  'tag-grid-table-dp': [],
  'tag-gcd-diophantine': [],
  'tag-geometry-orientation-transform': [],
  'tag-graph-core-peeling': [],
  'tag-graph-model-structure': [],
  'tag-greedy-exchange-order': [],
  'tag-inclusion-exclusion': [],
  'tag-integer-boundary-blocks': [],
  'tag-implicit-binary-tree-arithmetic': [],
  'tag-interactive-protocol': [],
  'tag-interval-partition-dp': [],
  'tag-knapsack-resource': [],
  'tag-lazy-segment-action': [],
  'tag-linear-algebra-xor': [],
  'tag-linear-recurrence-matrix': [],
  'tag-linked-list-index': [],
  'tag-lowlink-critical-structure': [],
  'tag-math-geometry-transformation': [],
  'tag-mo-offline-range': [],
  'tag-model-reduction': [],
  'tag-modular-arithmetic': [],
  'tag-modular-crt': [],
  'tag-monoid-segment-tree': [],
  'tag-monotone-stack-queue': [],
  'tag-monotone-threshold-search': [],
  'tag-ordered-set-heap': [],
  'tag-palindrome-radius': [],
  'tag-persistent-rollback': [],
  'tag-prefix-difference': [],
  'tag-prefix-matching-automata': [],
  'tag-prime-divisor-decomposition': [],
  'tag-query-sufficient-aggregate': ['更新可能な区間集約の設計'],
  'tag-reachability-bfs': [],
  'tag-randomized-algorithm': [],
  'tag-recursive-compressed-string': [],
  'tag-reverse-offline': [],
  'tag-sequence-subsequence-dp': [],
  'tag-shortest-path': [],
  'tag-shortest-path-certificate': [],
  'tag-spanning-tree-optimization': [],
  'tag-static-top-tree': [],
  'tag-stochastic-expectation-dp': [],
  'tag-string-hash-equality': [],
  'tag-string-state-representation': [],
  'tag-string-automata': [],
  'tag-subset-bitmask-transform': [],
  'tag-suffix-lcp-index': [],
  'tag-event-sweep': [],
  'tag-symmetry-invariant-normalization': [],
  'tag-tree-aggregation-reroot': [],
  'tag-tree-balanced-separator': [],
  'tag-tree-metric-diameter': [],
  'tag-tree-path-decomposition': [],
  'tag-trie-prefix': [],
  'tag-two-pointers-window': [],
  'tag-witness-impact-localization': [],
};

export const FINAL_TAG_REPRESENTATIVE_PROBLEM_IDS: Readonly<Record<string, readonly string[]>> = {
  'tag-amortized-heavy-light': ['abc217-e', 'abc329-f', 'abc219-g'],
  'tag-bounded-enumeration': ['abc234-e', 'abc328-e', 'abc353-f', 'abc386-e', 'abc442-g'],
  'tag-bipartite-structure': ['abc451-f', 'abc398-e', 'abc398-g'],
  'tag-binary-trie': ['abc425-g', 'abc254-ex'],
  'tag-bitset-word-parallel': ['abc258-g', 'abc348-f'],
  'tag-cartesian-tree': ['abc275-ex', 'abc420-f'],
  'tag-carry-mixed-radix-dp': ['abc231-e', 'abc466-g'],
  'tag-combinatorial-coefficients': ['abc358-e', 'abc234-f', 'abc217-g'],
  'tag-constructive-witness': ['abc333-e', 'abc239-f', 'abc244-g'],
  'tag-coordinate-compression': ['abc221-e', 'abc287-g', 'abc351-f', 'abc374-f'],
  'tag-contribution-reordering': ['abc233-e', 'abc224-f', 'abc215-g'],
  'tag-convex-hull-halfplane': ['abc251-g', 'abc275-g', 'abc356-g'],
  'tag-convex-hull-trick': ['abc289-g', 'abc228-h', 'abc372-g'],
  'tag-convolution-fps': ['abc392-g', 'abc291-g', 'abc213-h'],
  'tag-cyclic-group-order': ['abc212-g', 'abc222-g', 'abc335-g'],
  'tag-determinant-counting': ['abc216-h', 'abc253-ex', 'abc323-g'],
  'tag-digit-dp': ['abc235-f', 'abc336-e', 'abc406-e'],
  'tag-directed-condensation-toposort': ['abc291-e', 'abc245-f', 'abc277-ex', 'abc374-g'],
  'tag-discrete-convex-marginal': ['abc389-e', 'abc373-f', 'abc217-h'],
  'tag-divide-enumerate': [
    'abc271-f',
    'abc282-ex',
    'abc267-ex',
    'abc300-g',
    'abc252-ex',
    'abc270-g',
  ],
  'tag-dp-state-equivalence': ['abc375-e', 'abc232-e', 'abc296-ex'],
  'tag-dp-state-transition': ['abc375-e', 'abc253-e', 'abc391-g'],
  'tag-dp-transition-acceleration': ['abc212-e', 'abc353-g', 'abc221-h'],
  'tag-dsu-connectivity': ['abc392-e', 'abc328-f', 'abc314-f'],
  'tag-euler-degree-parity': ['abc286-g', 'abc345-f', 'abc227-h'],
  'tag-fenwick-weighted-prefix': ['abc221-e', 'abc256-f', 'abc287-g'],
  'tag-finite-field-extension': ['abc274-ex', 'abc381-g'],
  'tag-flow-matching-cut': ['abc241-g', 'abc239-g', 'abc231-h'],
  'tag-functional-graph-doubling': ['abc296-e', 'abc212-f', 'abc310-g'],
  'tag-game-grundy-dp': ['abc354-e', 'abc380-f', 'abc297-g'],
  'tag-game-value-dp': ['abc349-e', 'abc303-g', 'abc261-ex'],
  'tag-grid-table-dp': ['abc227-f', 'abc311-e'],
  'tag-gcd-diophantine': ['abc254-f', 'abc340-f', 'abc315-g', 'abc388-f', 'abc306-g'],
  'tag-geometry-orientation-transform': ['abc223-e', 'abc351-e', 'abc220-g'],
  'tag-graph-core-peeling': ['abc266-f', 'abc419-g'],
  'tag-graph-model-structure': ['abc213-e', 'abc235-e', 'abc374-g'],
  'tag-greedy-exchange-order': ['abc214-e', 'abc268-f', 'abc290-ex'],
  'tag-inclusion-exclusion': ['abc455-e', 'abc246-f', 'abc230-g'],
  'tag-integer-boundary-blocks': ['abc230-e', 'abc293-f', 'abc239-ex'],
  'tag-implicit-binary-tree-arithmetic': ['abc220-e', 'abc321-e', 'abc424-e'],
  'tag-interactive-protocol': ['abc305-f', 'abc355-e'],
  'tag-interval-partition-dp': ['abc466-e', 'abc288-f', 'abc233-g'],
  'tag-knapsack-resource': ['abc321-f', 'abc322-e', 'abc383-f'],
  'tag-lazy-segment-action': ['abc340-e', 'abc382-f', 'abc237-g'],
  'tag-linear-algebra-xor': ['abc396-e', 'abc236-f', 'abc212-h'],
  'tag-linear-recurrence-matrix': ['abc293-e', 'abc256-g', 'abc270-ex'],
  'tag-linked-list-index': ['abc344-e', 'abc421-f'],
  'tag-lowlink-critical-structure': ['abc334-g', 'abc375-g', 'abc301-ex'],
  'tag-math-geometry-transformation': ['abc358-e', 'abc230-e', 'abc213-h'],
  'tag-mo-offline-range': ['abc242-g', 'abc293-g', 'abc405-g'],
  'tag-model-reduction': ['abc214-e', 'abc233-e', 'abc329-f'],
  'tag-modular-arithmetic': ['abc228-e', 'abc411-e'],
  'tag-modular-crt': ['abc286-f', 'abc423-g', 'abc245-ex'],
  'tag-monoid-segment-tree': ['abc261-e', 'abc223-f', 'abc292-ex'],
  'tag-monotone-stack-queue': ['abc359-e', 'abc379-f', 'abc248-ex'],
  'tag-monotone-threshold-search': ['abc373-e', 'abc236-e', 'abc395-f'],
  'tag-ordered-set-heap': ['abc281-e', 'abc308-g', 'abc431-g'],
  'tag-palindrome-radius': ['abc398-f', 'abc349-g'],
  'tag-persistent-rollback': ['abc273-e', 'abc453-g', 'abc302-ex'],
  'tag-prefix-difference': ['abc341-e', 'abc430-f', 'abc260-g'],
  'tag-prefix-matching-automata': ['abc430-e', 'abc284-f', 'abc257-g'],
  'tag-prime-divisor-decomposition': ['abc445-e', 'abc259-e', 'abc227-g'],
  'tag-query-sufficient-aggregate': ['abc341-e', 'abc223-f', 'abc453-g'],
  'tag-reachability-bfs': ['abc284-e', 'abc302-f', 'abc317-e', 'abc361-g'],
  'tag-randomized-algorithm': ['abc272-g', 'abc422-e'],
  'tag-recursive-compressed-string': ['abc450-e', 'abc346-f', 'abc417-g'],
  'tag-reverse-offline': ['abc229-e', 'abc346-e', 'abc375-f'],
  'tag-sequence-subsequence-dp': ['abc271-e', 'abc354-f', 'abc240-ex'],
  'tag-shortest-path': ['abc213-e', 'abc237-e', 'abc325-e'],
  'tag-shortest-path-certificate': ['abc252-e', 'abc218-f', 'abc308-ex'],
  'tag-spanning-tree-optimization': ['abc218-e', 'abc282-e', 'abc352-e'],
  'tag-static-top-tree': ['abc351-g', 'abc460-g'],
  'tag-stochastic-expectation-dp': ['abc266-e', 'abc298-e', 'abc226-h'],
  'tag-string-hash-equality': ['abc367-f', 'abc455-g', 'abc274-ex'],
  'tag-string-state-representation': ['abc430-e', 'abc398-f', 'abc362-g'],
  'tag-string-automata': ['abc305-g', 'abc419-f', 'abc433-g'],
  'tag-subset-bitmask-transform': ['abc219-e', 'abc381-f', 'abc295-ex'],
  'tag-suffix-lcp-index': ['abc272-f', 'abc362-g', 'abc268-ex'],
  'tag-event-sweep': ['abc320-e', 'abc231-f', 'abc346-g'],
  'tag-symmetry-invariant-normalization': ['abc242-e', 'abc296-f', 'abc382-g'],
  'tag-tree-aggregation-reroot': ['abc239-e', 'abc220-f', 'abc223-g'],
  'tag-tree-balanced-separator': ['abc359-g', 'abc291-ex'],
  'tag-tree-metric-diameter': ['abc221-f', 'abc267-f', 'abc401-f'],
  'tag-tree-path-decomposition': ['abc294-g', 'abc298-ex', 'abc340-g', 'abc351-g', 'abc405-f'],
  'tag-trie-prefix': ['abc287-e', 'abc353-e', 'abc437-e'],
  'tag-two-pointers-window': ['abc260-e', 'abc250-f', 'abc370-f'],
  'tag-witness-impact-localization': ['abc279-e', 'abc218-f'],
};

export type FinalTagRelationType =
  'contrast' | 'specialization' | 'analogy' | 'often_combined' | 'implementation_substrate';

export interface FinalTagRelationSeed {
  readonly sourceTagId: string;
  readonly targetTagId: string;
  readonly type: FinalTagRelationType;
  readonly rationale: string;
}

/** Peer relations are materialized in both directions for direct use from either Tag page. */
export const FINAL_TAG_SYMMETRIC_RELATION_SEEDS: readonly FinalTagRelationSeed[] = [
  {
    sourceTagId: 'tag-monotone-threshold-search',
    targetTagId: 'tag-two-pointers-window',
    type: 'contrast',
    rationale:
      'どちらも単調性を使うが、値域の真偽境界を探す方法と連続区間の端を一方向へ進める方法を区別する。',
  },
  {
    sourceTagId: 'tag-bounded-enumeration',
    targetTagId: 'tag-meet-in-the-middle',
    type: 'contrast',
    rationale:
      '候補全体を制約から直接界す全列挙と、探索空間を二分して部分結果を照合する半分全列挙を区別する。',
  },
  {
    sourceTagId: 'tag-event-sweep',
    targetTagId: 'tag-coordinate-compression',
    type: 'contrast',
    rationale:
      '順序付きeventに沿ってactive状態を更新する走査と、順序・等値性だけを保って添字化する圧縮を区別する。',
  },
  {
    sourceTagId: 'tag-digit-dp',
    targetTagId: 'tag-carry-mixed-radix-dp',
    type: 'contrast',
    rationale:
      '上限との接頭辞一致を保つ桁DPと、下位桁から繰り上がりだけを渡す混合基数DPを区別する。',
  },
  {
    sourceTagId: 'tag-digit-dp',
    targetTagId: 'tag-automaton-dp',
    type: 'contrast',
    rationale: '数値上限のtight状態を扱うDPと、受理条件を表す有限automatonとの直積DPを区別する。',
  },
  {
    sourceTagId: 'tag-game-grundy-dp',
    targetTagId: 'tag-game-value-dp',
    type: 'contrast',
    rationale:
      'impartial gameのGrundy数と、双方の目的が異なる局面のminimax値を同じゲームDPへ混同しない。',
  },
  {
    sourceTagId: 'tag-persistence',
    targetTagId: 'tag-rollback',
    type: 'contrast',
    rationale:
      '過去版を共有して保持する永続化と、現在状態をundoして探索順に戻すrollbackを区別する。',
  },
  {
    sourceTagId: 'tag-graph-potential-propagation',
    targetTagId: 'tag-potential-dsu',
    type: 'contrast',
    rationale:
      '固定graph上で等式を一括伝播する方法と、辺追加に追随して差分potentialを保つ方法を区別する。',
  },
  {
    sourceTagId: 'tag-convex-boundary-hull',
    targetTagId: 'tag-half-plane-constraints',
    type: 'contrast',
    rationale:
      '目的関数の候補を凸境界へ絞る見方と、線形半平面の共通部分として可行領域を表す見方を区別する。',
  },
  {
    sourceTagId: 'tag-bipartite-matching-hall',
    targetTagId: 'tag-min-weight-general-perfect-matching',
    type: 'contrast',
    rationale:
      '二部性を使えるaugmenting path・Hall型議論と、odd blossomを扱う一般graph完全matchingを対比する。',
  },
  {
    sourceTagId: 'tag-subset-zeta-mobius-transform',
    targetTagId: 'tag-divisor-mobius-inversion',
    type: 'analogy',
    rationale:
      'subset包含順序と約数整除順序はいずれもposet上のzeta変換とMöbius反転として統一して捉えられる。',
  },
  {
    sourceTagId: 'tag-rollback',
    targetTagId: 'tag-backtracking-search',
    type: 'analogy',
    rationale:
      '再帰へ入る前の更新と復帰時のundoを対にし、現在pathだけの不変条件を保つ設計が共通する。',
  },
  {
    sourceTagId: 'tag-binary-lifting',
    targetTagId: 'tag-monoid-exponentiation',
    type: 'analogy',
    rationale: '2冪長の遷移を前計算し、指数のbit分解で必要な合成だけを選ぶ構造が共通する。',
  },
  {
    sourceTagId: 'tag-semiring-matrix-exponentiation',
    targetTagId: 'tag-monoid-exponentiation',
    type: 'analogy',
    rationale:
      '閉じた結合的合成を二分累乗する共通原理を、行列半環と一般monoidの二つの表現から比較する。',
  },
  {
    sourceTagId: 'tag-z-algorithm-prefix-matching',
    targetTagId: 'tag-suffix-lcp-index',
    type: 'analogy',
    rationale: '一つのprefixとの一致長列と、全suffix間の辞書順・LCP索引を目的に応じて使い分ける。',
  },
  {
    sourceTagId: 'tag-graph-core-peeling',
    targetTagId: 'tag-directed-core-peeling',
    type: 'analogy',
    rationale: '局所次数条件を満たさない頂点をqueueで除き、残存核の不変条件を読む発想が共通する。',
  },
  {
    sourceTagId: 'tag-event-sweep',
    targetTagId: 'tag-coordinate-compression',
    type: 'often_combined',
    rationale:
      '疎なevent座標を圧縮してFenwick TreeやSegment Tree上でactive情報を更新する構成で頻繁に併用する。',
  },
  {
    sourceTagId: 'tag-event-sweep',
    targetTagId: 'tag-ordered-set-multiset',
    type: 'often_combined',
    rationale:
      'eventの追加・削除に応じてactive候補の最小値・近傍・順位を動的に保つ構成で併用する。',
  },
  {
    sourceTagId: 'tag-coordinate-compression',
    targetTagId: 'tag-fenwick-weighted-prefix',
    type: 'often_combined',
    rationale: '疎な値を順序保存圧縮してから、個数・重み・反転数をprefix集約する構成で併用する。',
  },
  {
    sourceTagId: 'tag-monotone-threshold-search',
    targetTagId: 'tag-dsu-components',
    type: 'often_combined',
    rationale: '閾値以下の辺だけを有効化する単調判定器をDSUで共有するときに併用する。',
  },
  {
    sourceTagId: 'tag-generating-functions',
    targetTagId: 'tag-convolution',
    type: 'often_combined',
    rationale: '組合せの合成を生成関数の積へ符号化し、その係数を畳み込みで計算する流れで併用する。',
  },
  {
    sourceTagId: 'tag-inclusion-exclusion',
    targetTagId: 'tag-subset-zeta-mobius-transform',
    type: 'often_combined',
    rationale:
      '条件集合全体の包除をsubset lattice上で一括計算するときにzeta・Möbius変換を併用する。',
  },
  {
    sourceTagId: 'tag-convex-hull-trick',
    targetTagId: 'tag-dp-transition-acceleration',
    type: 'often_combined',
    rationale: 'DP遷移を直線の評価へ変形し、包絡線queryとして高速化する構成で併用する。',
  },
  {
    sourceTagId: 'tag-max-flow-min-cut',
    targetTagId: 'tag-bipartite-matching-hall',
    type: 'often_combined',
    rationale:
      '二部matchingをunit-capacity flowへ帰着し、Kőnig型双対をmin-cutから説明するときに併用する。',
  },
  {
    sourceTagId: 'tag-suffix-lcp-index',
    targetTagId: 'tag-idempotent-overlap-range-query',
    type: 'often_combined',
    rationale:
      'suffix array上の二suffixのLCPを、隣接LCP列の区間最小値queryとして求めるときに併用する。',
  },
  {
    sourceTagId: 'tag-tree-euler-flattening',
    targetTagId: 'tag-range-monoid-aggregation',
    type: 'often_combined',
    rationale: '部分木を連続区間へ写し、区間集約・一点更新・差分伝播へ接続するときに併用する。',
  },
  {
    sourceTagId: 'tag-small-to-large',
    targetTagId: 'tag-rooted-tree-aggregation',
    type: 'often_combined',
    rationale: '子部分木の集合・mapを小さい側から大きい側へmergeする木DPで併用する。',
  },
  {
    sourceTagId: 'tag-interactive-protocol',
    targetTagId: 'tag-information-theoretic-query-design',
    type: 'often_combined',
    rationale: 'query回数の情報量下界とcodeword構成を、実際の対話protocolへ落とすときに併用する。',
  },
  {
    sourceTagId: 'tag-ordered-set-multiset',
    targetTagId: 'tag-ordered-interval-partition',
    type: 'often_combined',
    rationale: '区間端点をordered setで管理し、split・mergeする区間族を動的に保つときに併用する。',
  },
  {
    sourceTagId: 'tag-state-graph-search',
    targetTagId: 'tag-shortest-path',
    type: 'often_combined',
    rationale:
      '問題状態を頂点、合法操作を辺へ写してから、辺重みに応じた最短路algorithmを選ぶ流れで併用する。',
  },
  {
    sourceTagId: 'tag-spanning-tree-optimization',
    targetTagId: 'tag-dsu-components',
    type: 'often_combined',
    rationale:
      'Kruskal順に採用済み成分を管理する実装ではDSUを併用するが、cut・cycle性質そのものとは分けて学ぶ。',
  },
];

/** Directed semantics: source specializes target, or source uses target as an implementation substrate. */
export const FINAL_TAG_DIRECTED_RELATION_SEEDS: readonly FinalTagRelationSeed[] = [
  {
    sourceTagId: 'tag-parallel-binary-search',
    targetTagId: 'tag-monotone-threshold-search',
    type: 'specialization',
    rationale: '単一queryの単調境界探索を、多数queryで判定器を共有するround処理へ特殊化する。',
  },
  {
    sourceTagId: 'tag-fractional-parametric-search',
    targetTagId: 'tag-monotone-threshold-search',
    type: 'specialization',
    rationale: '比率目的を加法判定へ変換した上で単調境界探索を適用する特殊化である。',
  },
  {
    sourceTagId: 'tag-directional-grid-effect-scan',
    targetTagId: 'tag-event-sweep',
    type: 'specialization',
    rationale: 'active状態を更新するevent sweepの見方を、各行・各列の固定方向scanへ特殊化する。',
  },
  {
    sourceTagId: 'tag-weighted-bipartite-matching',
    targetTagId: 'tag-bipartite-matching-hall',
    type: 'specialization',
    rationale: '二部matchingに辺重みと完全割当の目的を加えた最適化版として学ぶ。',
  },
  {
    sourceTagId: 'tag-flow-feasibility-lower-bounds',
    targetTagId: 'tag-max-flow-min-cut',
    type: 'specialization',
    rationale: '通常の容量制約に下限と需要balanceを加え、補助source・sinkで実現可能性を判定する。',
  },
  {
    sourceTagId: 'tag-min-cost-flow',
    targetTagId: 'tag-max-flow-min-cut',
    type: 'specialization',
    rationale: 'flow量の実現に加えて費用最小化を扱う拡張として位置付ける。',
  },
  {
    sourceTagId: 'tag-dynamic-segment-tree',
    targetTagId: 'tag-range-monoid-aggregation',
    type: 'specialization',
    rationale: '必要な節点だけを生成し、巨大・疎な添字域へ区間monoid集約を拡張する。',
  },
  {
    sourceTagId: 'tag-segment-tree-beats',
    targetTagId: 'tag-range-monoid-aggregation',
    type: 'specialization',
    rationale: '通常の一様な遅延作用で閉じないchmin/chmax更新を、追加要約で処理する特殊化である。',
  },
  {
    sourceTagId: 'tag-aho-corasick',
    targetTagId: 'tag-finite-pattern-automaton',
    type: 'specialization',
    rationale: '複数patternの共有prefixとfailure linkを持つ有限automatonとして特殊化する。',
  },
  {
    sourceTagId: 'tag-finite-field-frobenius',
    targetTagId: 'tag-finite-field-extension',
    type: 'specialization',
    rationale: '拡大有限体上のp乗写像とその軌道構造に焦点を当てた特殊化である。',
  },
  {
    sourceTagId: 'tag-fps-composition-power-projection',
    targetTagId: 'tag-formal-power-series',
    type: 'specialization',
    rationale: '基本FPS演算を前提に、合成・power projectionという高次演算へ進む。',
  },
  {
    sourceTagId: 'tag-relaxed-convolution',
    targetTagId: 'tag-convolution',
    type: 'specialization',
    rationale: '係数が逐次確定する依存を保ったまま畳み込みをonline計算する特殊化である。',
  },
  {
    sourceTagId: 'tag-subset-convolution',
    targetTagId: 'tag-convolution',
    type: 'specialization',
    rationale: '添字加算ではなくdisjoint subset分割を合成則にした畳み込みへ特殊化する。',
  },
  {
    sourceTagId: 'tag-bostan-mori',
    targetTagId: 'tag-generating-functions',
    type: 'specialization',
    rationale: '有理生成関数の巨大次数係数を偶奇分離で抽出する目的へ特殊化する。',
  },
  {
    sourceTagId: 'tag-steiner-tree-dp',
    targetTagId: 'tag-subset-bitmask-dp',
    type: 'specialization',
    rationale: 'terminal subsetを状態にし、部分集合分割と最短路closureを組み合わせる特殊化である。',
  },
  {
    sourceTagId: 'tag-static-top-tree',
    targetTagId: 'tag-rooted-tree-aggregation',
    type: 'specialization',
    rationale: '木DPの合成則をboundary付きclusterへ持ち上げ、局所変更へ対応する特殊化である。',
  },
  {
    sourceTagId: 'tag-kruskal-threshold-sweep',
    targetTagId: 'tag-spanning-tree-optimization',
    type: 'specialization',
    rationale: 'Kruskal順のprefixを閾値部分graphとして利用するMST系の特殊化である。',
  },
  {
    sourceTagId: 'tag-difference-constraints',
    targetTagId: 'tag-shortest-path',
    type: 'specialization',
    rationale: '差の不等式を緩和辺へ写し、最短路の不変条件で可解性と極値を求める特殊化である。',
  },
  {
    sourceTagId: 'tag-lazy-segment-action',
    targetTagId: 'tag-range-monoid-aggregation',
    type: 'implementation_substrate',
    rationale: '区間要約のmonoidと、その要約へ作用する写像を基盤として遅延更新を実装する。',
  },
  {
    sourceTagId: 'tag-static-sorted-range-index',
    targetTagId: 'tag-segment-tree-canonical-decomposition',
    type: 'implementation_substrate',
    rationale: 'query区間をcanonical node列へ分け、各nodeのsorted列を二分探索する実装に使う。',
  },
  {
    sourceTagId: 'tag-virtual-tree',
    targetTagId: 'tag-tree-ancestor-lca',
    type: 'implementation_substrate',
    rationale: '選択頂点集合を祖先関係を保つ小木へ閉じるため、隣接頂点間のLCAを挿入する。',
  },
  {
    sourceTagId: 'tag-virtual-tree',
    targetTagId: 'tag-tree-euler-flattening',
    type: 'implementation_substrate',
    rationale: '祖先順を保ったstack構築のため、選択頂点をEuler in順に並べる。',
  },
  {
    sourceTagId: 'tag-heavy-light-decomposition',
    targetTagId: 'tag-tree-euler-flattening',
    type: 'implementation_substrate',
    rationale: 'heavy pathごとの頂点を連続indexへ写し、pathを少数区間へ分解する。',
  },
  {
    sourceTagId: 'tag-heavy-light-decomposition',
    targetTagId: 'tag-range-monoid-aggregation',
    type: 'implementation_substrate',
    rationale: '分解した各heavy path区間の値を方向付きmonoid queryで合成する。',
  },
  {
    sourceTagId: 'tag-aho-corasick',
    targetTagId: 'tag-trie-prefix',
    type: 'implementation_substrate',
    rationale: '複数patternの共有prefixをTrieにまとめ、failure linkを加えてautomatonを構築する。',
  },
  {
    sourceTagId: 'tag-automaton-dp',
    targetTagId: 'tag-finite-pattern-automaton',
    type: 'implementation_substrate',
    rationale: '位置・長さと直積する有限状態および完全遷移表をDPの状態基盤にする。',
  },
  {
    sourceTagId: 'tag-min-cost-flow',
    targetTagId: 'tag-shortest-path',
    type: 'implementation_substrate',
    rationale: 'potentialで非負化した残余graph上の最短路を、増加路選択の実装基盤にする。',
  },
  {
    sourceTagId: 'tag-potential-dsu',
    targetTagId: 'tag-dsu-components',
    type: 'implementation_substrate',
    rationale: '通常のDSUにrootまでの差分potentialを持たせ、merge時にoffsetを調整する。',
  },
  {
    sourceTagId: 'tag-kruskal-threshold-sweep',
    targetTagId: 'tag-dsu-components',
    type: 'implementation_substrate',
    rationale: '辺重み順に追加される閾値部分graphの連結成分をDSUで増分管理する。',
  },
  {
    sourceTagId: 'tag-polynomial-multipoint-evaluation',
    targetTagId: 'tag-recursive-divide-and-conquer',
    type: 'implementation_substrate',
    rationale: 'subproduct treeとremainder treeをbalancedに構築する基盤として再帰分割を使う。',
  },
  {
    sourceTagId: 'tag-polynomial-multipoint-evaluation',
    targetTagId: 'tag-convolution',
    type: 'implementation_substrate',
    rationale: '積木と剰余計算の多項式積を高速化する基盤として畳み込みを使う。',
  },
  {
    sourceTagId: 'tag-polynomial-taylor-shift',
    targetTagId: 'tag-convolution',
    type: 'implementation_substrate',
    rationale: '二項展開を階乗で正規化し、反転した係数列との一回の畳み込みへ落とす。',
  },
  {
    sourceTagId: 'tag-formal-power-series',
    targetTagId: 'tag-convolution',
    type: 'implementation_substrate',
    rationale: 'Newton iterationの各段で必要な積・逆数更新を高速多項式畳み込みで実装する。',
  },
  {
    sourceTagId: 'tag-poset-dilworth-antichain',
    targetTagId: 'tag-bipartite-matching-hall',
    type: 'implementation_substrate',
    rationale: 'posetのchain coverを二部matchingへ写し、Dilworth型双対を計算する。',
  },
  {
    sourceTagId: 'tag-tree-precedence-contraction',
    targetTagId: 'tag-dsu-components',
    type: 'implementation_substrate',
    rationale: 'cluster縮約後の代表と統計を管理し、既に統合した頂点を一つの成分として扱う。',
  },
  {
    sourceTagId: 'tag-path-matching-contraction',
    targetTagId: 'tag-priority-queue-best-first',
    type: 'implementation_substrate',
    rationale: '現在もっとも有利な局所matching候補をheapから取り出し、縮約後の候補を再挿入する。',
  },
];
