/** 全Unitを内容から査読した学習段階。目次の深さ・旧rankからは推定しない。
 * 段階は独立な技能間の編集順であり、prerequisite DAGを常に優先する。
 */
export const CURRICULUM_STAGES = [
  {
    rank: 0,
    rationale: '目次の案内。標準学習順には含めない。',
    unitIds: [
      'unit-chapter-combinatorics-algebra',
      'unit-chapter-dynamic-programming',
      'unit-chapter-geometry-optimization',
      'unit-chapter-graph',
      'unit-chapter-modeling',
      'unit-chapter-number-theory',
      'unit-chapter-query',
      'unit-chapter-string',
      'unit-chapter-tree',
      'unit-connectivity',
      'unit-convex-geometry',
      'unit-decomposition-amortization',
      'unit-directed-condensation',
      'unit-discrete-convex',
      'unit-divide-enumeration',
      'unit-dp-digit-string',
      'unit-dp-sequence-interval',
      'unit-euler-degree',
      'unit-flow-matching',
      'unit-functional-graph',
      'unit-graph-core-peeling',
      'unit-graph-search',
      'unit-linear-algebra-xor',
      'unit-matroid-theory',
      'unit-modular-product-foundations',
      'unit-monoid-segment-tree',
      'unit-ordered-set-heap',
      'unit-persistence-rollback',
      'unit-shortest-path-certificates',
      'unit-string-automata',
      'unit-string-hash',
      'unit-string-prefix-automata',
      'unit-tree-aggregation',
      'unit-tree-decomposition',
    ],
  },
  {
    rank: 1,
    rationale: '状態・順序・集約の基礎。多分野で繰り返し使う定式化と基本操作を学ぶ。',
    unitIds: [
      'unit-amortized-monotone-progress',
      'unit-backtracking-search',
      'unit-bipartite-structure',
      'unit-bounded-enumeration',
      'unit-combinatorial-coefficients',
      'unit-constructive-witness',
      'unit-contribution-reordering',
      'unit-coordinate-compression',
      'unit-dag-topological-processing',
      'unit-dp-grid-table',
      'unit-dp-prefix-partition',
      'unit-dp-sequence',
      'unit-dp-state-design',
      'unit-dsu-components',
      'unit-gcd-diophantine',
      'unit-gcd-structure',
      'unit-geometry-primitives',
      'unit-graph-potential-propagation',
      'unit-greedy-exchange',
      'unit-linked-list-index',
      'unit-meet-in-the-middle',
      'unit-modular-arithmetic',
      'unit-monotone-search',
      'unit-monotone-stack-queue',
      'unit-normalization',
      'unit-ordered-set-multiset',
      'unit-prefix-aggregate',
      'unit-prime-divisor',
      'unit-priority-queue-best-first',
      'unit-recursive-divide-and-conquer',
      'unit-state-graph-search',
      'unit-trie-prefix',
      'unit-two-pointers-window',
      'unit-z-algorithm',
    ],
  },
  {
    rank: 2,
    rationale: '標準算法。基本データ構造、主要なDP、最短路・SCC・木・matchingとflowを揃える。',
    unitIds: [
      'unit-binary-lifting',
      'unit-binary-trie',
      'unit-bipartite-matching',
      'unit-bitset-word-parallel',
      'unit-digit-dp',
      'unit-directed-core-peeling',
      'unit-dp-carry-mixed-radix',
      'unit-dp-game',
      'unit-dp-game-value',
      'unit-dp-interval-composition',
      'unit-dp-interval-expansion',
      'unit-dp-lis',
      'unit-dp-stochastic',
      'unit-dp-subset-resource',
      'unit-dp-subset-state',
      'unit-dp-value-range',
      'unit-dynamic-modular-product',
      'unit-euler-trail-circuit',
      'unit-event-sweep',
      'unit-finite-function-composition',
      'unit-finite-pattern-automaton',
      'unit-functional-graph-decomposition',
      'unit-graph-core',
      'unit-idempotent-overlap-range-query',
      'unit-inclusion-exclusion',
      'unit-integer-boundary-blocks',
      'unit-linear-system-rank',
      'unit-max-flow-min-cut',
      'unit-modular-congruence',
      'unit-monoid-exponentiation',
      'unit-palindrome-radius',
      'unit-potential-dsu',
      'unit-range-actions',
      'unit-range-monoid-aggregation',
      'unit-rerooting',
      'unit-reverse-offline',
      'unit-rooted-tree-aggregation',
      'unit-scc-condensation',
      'unit-sequence-fingerprint',
      'unit-shortest-path-reconstruction',
      'unit-spanning-tree-optimization',
      'unit-transitive-closure',
      'unit-tree-ancestor-lca',
      'unit-tree-euler-flattening',
      'unit-tree-metric',
      'unit-weighted-prefix-fenwick',
      'unit-value-bucket-aggregation',
      'unit-weighted-shortest-path',
      'unit-xor-linear-basis',
    ],
  },
  {
    rank: 3,
    rationale: '標準技能の応用。複合データ構造、変換、数論・幾何の個別原理へ進む。',
    unitIds: [
      'unit-aho-corasick',
      'unit-automaton-dp',
      'unit-baby-step-giant-step',
      'unit-basic-convex-optimization',
      'unit-binary-tree-ancestor-matching',
      'unit-bitwise-greedy-feasibility',
      'unit-bitwise-minimax-partition',
      'unit-cartesian-tree',
      'unit-change-impact-localization',
      'unit-convex-boundary-hull',
      'unit-cycle-space-basis',
      'unit-cyclic-minimax-game',
      'unit-cyclic-order-crossing',
      'unit-degree-parity-subgraph',
      'unit-difference-constraints',
      'unit-directed-walk-periodicity',
      'unit-directional-grid-effect-scan',
      'unit-divisor-mobius-inversion',
      'unit-dp-transition-optimization',
      'unit-dsu-merge-tree',
      'unit-dynamic-segment-tree',
      'unit-flow-lower-bounds',
      'unit-fractional-parametric-search',
      'unit-generating-functions',
      'unit-half-plane-constraints',
      'unit-heavy-light-decomposition',
      'unit-implicit-binary-tree',
      'unit-information-theoretic-query-design',
      'unit-interactive-protocol',
      'unit-kruskal-threshold-sweep',
      'unit-laminar-interval-containment-tree',
      'unit-line-envelope',
      'unit-linear-recurrence',
      'unit-lowlink-critical-structure',
      'unit-min-cost-flow',
      'unit-mo-offline-range',
      'unit-modular-periodicity',
      'unit-monotone-path-contraction',
      'unit-multiplicative-order-periods',
      'unit-near-tree-kernelization',
      'unit-ordered-interval-partition',
      'unit-parallel-binary-search',
      'unit-persistence',
      'unit-polynomial-convolution',
      'unit-randomized-algebraic-fingerprint',
      'unit-randomized-algorithms',
      'unit-rational-approximation',
      'unit-euclidean-floor-sum',
      'unit-recursive-compressed-string',
      'unit-rollback',
      'unit-segment-tree-canonical-decomposition',
      'unit-semiring-matrix-exponentiation',
      'unit-separable-convex-marginals',
      'unit-separable-linear-transform',
      'unit-small-to-large',
      'unit-static-sorted-range-index',
      'unit-stern-brocot-ancestry',
      'unit-string-periodicity',
      'unit-subset-transforms',
      'unit-suffix-lcp-index',
      'unit-swag',
      'unit-threshold-heavy-light',
      'unit-tree-balanced-separators',
      'unit-two-sat',
      'unit-virtual-tree',
    ],
  },
  {
    rank: 4,
    rationale: '発展算法。強い構造条件や代数的道具を使う最適化・数え上げを学ぶ。',
    unitIds: [
      'unit-additive-tree-metric-reconstruction',
      'unit-additive-expectation-potential',
      'unit-automaton-subset-construction',
      'unit-bostan-mori',
      'unit-conway-number-games',
      'unit-cyclic-group-exponent-counting',
      'unit-deletion-contraction',
      'unit-determinant-counting',
      'unit-euler-circuit-counting',
      'unit-eventual-unbounded-knapsack',
      'unit-finite-field-extension',
      'unit-finite-field-frobenius',
      'unit-formal-power-series',
      'unit-frontier-profile-dp',
      'unit-gaussian-integers-two-squares',
      'unit-heavy-light-recursive-dp',
      'unit-heavy-path-tree-dp',
      'unit-isotonic-regression',
      'unit-kinetic-order-maintenance',
      'unit-labeled-component-decomposition',
      'unit-lagrangian-relaxation',
      'unit-matroid-greedy',
      'unit-min-weight-general-perfect-matching',
      'unit-monge-optimization',
      'unit-numerical-semigroup-reachability',
      'unit-orbit-counting',
      'unit-path-matching-contraction',
      'unit-planar-duality',
      'unit-polynomial-multipoint-evaluation',
      'unit-polynomial-taylor-shift',
      'unit-poset-dilworth-antichain',
      'unit-prufer-code',
      'unit-reflection-principle',
      'unit-relaxed-convolution',
      'unit-run-length-dynamics',
      'unit-segment-tree-beats',
      'unit-slope-trick',
      'unit-static-top-tree',
      'unit-steiner-tree-dp',
      'unit-subset-convolution',
      'unit-suffix-automaton',
      'unit-tree-precedence-contraction',
      'unit-weighted-bipartite-matching',
    ],
  },
  {
    rank: 5,
    rationale: '専門的な発展。高度な数論・組合せ対応・形式的冪級数の算法を扱う。',
    unitIds: [
      'unit-fps-composition-power-projection',
      'unit-generating-function-coefficients',
      'unit-linear-matroid-intersection',
      'unit-min25-sieve',
      'unit-rsk-young-tableaux',
    ],
  },
] as const;

const stageByUnitId = new Map<string, (typeof CURRICULUM_STAGES)[number]>();
for (const stage of CURRICULUM_STAGES) {
  for (const id of stage.unitIds) {
    if (stageByUnitId.has(id)) throw new Error(`DUPLICATE_CURRICULUM_STAGE:${id}`);
    stageByUnitId.set(id, stage);
  }
}

export const curriculumStageForUnit = (unitId: string) => {
  const stage = stageByUnitId.get(unitId);
  if (stage === undefined) throw new Error(`UNREVIEWED_CURRICULUM_STAGE:${unitId}`);
  return stage;
};
