export const FINAL_TAG_LEARNER_ALIASES: Readonly<Record<string, readonly string[]>> = {
  'tag-amortized-heavy-light': [
    '償却解析',
    '平方根分割',
    'amortized analysis',
    'sqrt decomposition',
  ],
  'tag-bounded-enumeration': [
    '制約を利用した全探索',
    '小さい候補集合の全列挙',
    'bounded exhaustive search',
    'finite case enumeration',
  ],
  'tag-bipartite-structure': ['二部グラフ', '二部彩色', 'bipartite graph', '2-coloring'],
  'tag-binary-trie': ['01-Trie', 'bitwise trie', 'XOR Trie'],
  'tag-bitset-word-parallel': ['ビット集合', 'word-parallel algorithm', 'bitset optimization'],
  'tag-cartesian-tree': ['デカルト木', 'Cartesian tree', 'min Cartesian tree'],
  'tag-carry-mixed-radix-dp': ['繰り上がりDP', '混合基数DP', 'carry DP', 'mixed-radix DP'],
  'tag-combinatorial-coefficients': ['二項係数', '重複組合せ', 'binomial coefficients'],
  'tag-constructive-witness': ['構築問題', 'constructive algorithms'],
  'tag-coordinate-compression': [
    '座標圧縮',
    '値圧縮',
    'coordinate compression',
    'rank compression',
  ],
  'tag-contribution-reordering': ['主客転倒', 'contribution technique'],
  'tag-convex-hull-halfplane': [
    '凸幾何',
    '半平面交差',
    'convex geometry',
    'half-plane intersection',
  ],
  'tag-convex-hull-trick': ['Convex Hull Trick', 'CHT', '直線包絡'],
  'tag-convolution-fps': [
    '形式的冪級数',
    'formal power series',
    '多項式畳み込み',
    'multipoint evaluation',
    'NTT',
    'FFT',
  ],
  'tag-cyclic-group-order': ['乗法的位数', 'multiplicative order', 'primitive root'],
  'tag-determinant-counting': [
    '行列式による数え上げ',
    '行列木定理',
    'Matrix-Tree theorem',
    'LGV lemma',
  ],
  'tag-digit-automaton-dp': ['桁DP', 'digit DP', 'オートマトンDP'],
  'tag-directed-condensation-toposort': [
    '強連結成分分解',
    'SCC',
    'トポロジカルソート',
    'topological sort',
    '2-SAT',
    '含意グラフ',
    'implication graph',
  ],
  'tag-discrete-convex-marginal': ['スロープトリック', 'Slope Trick', 'convex cost'],
  'tag-divide-enumerate': [
    '半分全列挙',
    'meet-in-the-middle',
    'MITM',
    '分割統治',
    'divide and conquer',
  ],
  'tag-dp-state-equivalence': ['状態圧縮DP', 'state-compressed DP', 'minimal sufficient state'],
  'tag-dp-state-transition': ['動的計画法', 'dynamic programming', 'DP'],
  'tag-dp-transition-acceleration': ['DP高速化', 'DP optimization', 'Monge optimization'],
  'tag-dsu-connectivity': [
    'Union-Find',
    '素集合データ構造',
    'disjoint set union',
    '連結成分縮約',
    'component contraction',
  ],
  'tag-euler-degree-parity': ['オイラー路', '一筆書き', 'Eulerian trail'],
  'tag-fenwick-weighted-prefix': ['フェニック木', 'Binary Indexed Tree', 'BIT'],
  'tag-finite-field-extension': [
    '有限体拡大',
    'extension field',
    'quadratic finite field',
    'Nim product',
  ],
  'tag-flow-matching-cut': ['最大流', '最小カット', '二部マッチング', 'max flow'],
  'tag-functional-graph-doubling': ['写像のダブリング', 'functional graph', 'binary lifting'],
  'tag-game-grundy-dp': ['ゲームDP', '組合せゲーム', 'combinatorial game DP', 'Nim'],
  'tag-game-value-dp': ['minimax', 'ミニマックス', '得点差ゲームDP', 'partisan game'],
  'tag-grid-table-dp': ['グリッドDP', '二次元DP', 'grid DP', 'table DP'],
  'tag-gcd-diophantine': [
    '最大公約数',
    'ユークリッドの互除法',
    'Euclidean algorithm',
    'Diophantine equation',
    '数値半群',
    'Frobeniusの硬貨問題',
    'numerical semigroup',
    'Frobenius coin problem',
    'conductor',
  ],
  'tag-geometry-orientation-transform': [
    '計算幾何',
    '外積判定',
    'computational geometry',
    'Manhattan transform',
  ],
  'tag-graph-core-peeling': [
    '2-core',
    '葉刈り',
    'graph peeling',
    'graph kernelization',
    'cycle-rank kernel',
  ],
  'tag-graph-model-structure': ['グラフ理論', 'graph algorithms'],
  'tag-greedy-exchange-order': ['貪欲法', '交換法', 'greedy algorithm'],
  'tag-inclusion-exclusion': [
    '包除原理',
    'メビウス反転',
    'inclusion-exclusion principle',
    'Möbius inversion',
  ],
  'tag-integer-boundary-blocks': ['商が一定の区間', '整数平方根', 'floor quotient grouping'],
  'tag-implicit-binary-tree-arithmetic': [
    '暗黙の完全二分木',
    '完全二分木の深さ集約',
    'heap index tree',
    'implicit complete binary tree',
    'symmetric complete binary tree',
  ],
  'tag-interactive-protocol': [
    'インタラクティブ問題',
    '対話型問題',
    'interactive problem',
    'query protocol',
  ],
  'tag-interval-partition-dp': ['区間DP', '分割DP', 'interval DP'],
  'tag-knapsack-resource': ['ナップサックDP', '部分和DP', 'knapsack DP'],
  'tag-lazy-segment-action': ['遅延セグメント木', 'lazy segment tree', 'lazy propagation'],
  'tag-linear-algebra-xor': [
    'ガウス消去法',
    '線形基底',
    'Gaussian elimination',
    'XOR basis',
    'Kronecker積',
    'tensor-product transform',
  ],
  'tag-linear-recurrence-matrix': ['行列累乗', 'matrix exponentiation', 'Kitamasa method'],
  'tag-linked-list-index': ['連結リスト', 'linked list', 'doubly linked list'],
  'tag-lowlink-critical-structure': ['Low-Link', '橋・関節点', 'bridges and articulation points'],
  'tag-math-geometry-transformation': ['数学的帰着', '数式化', 'mathematical reduction'],
  'tag-mo-offline-range': ['Mo法', 'ムーのアルゴリズム', "Mo's algorithm"],
  'tag-model-reduction': ['問題の言い換え', 'modeling', 'problem reduction'],
  'tag-modular-arithmetic': [
    '法上の四則演算',
    'モジュラ逆元',
    '零を含む動的積',
    'modular arithmetic',
    'modular inverse',
    'modular exponentiation',
    'zero-aware modular product',
  ],
  'tag-modular-crt': ['一次合同式', '中国剰余定理', 'Chinese remainder theorem', 'CRT'],
  'tag-monoid-segment-tree': [
    'セグメント木',
    '線分木',
    'segment tree',
    'canonical区間分解',
    'segment tree canonical cover',
    'segment tree graph',
    '時間セグメント木',
  ],
  'tag-monotone-stack-queue': ['単調スタック', '単調キュー', 'monotonic stack', 'monotonic queue'],
  'tag-monotone-threshold-search': ['答えの二分探索', '二分探索', 'binary search on the answer'],
  'tag-ordered-set-heap': ['優先度付きキュー', '平衡二分探索木', 'priority queue', 'ordered set'],
  'tag-palindrome-radius': ['Manacher法', "Manacher's algorithm"],
  'tag-persistent-rollback': [
    '永続データ構造',
    'ロールバック',
    'persistent data structure',
    'rollback',
  ],
  'tag-prefix-difference': ['いもす法', '累積和', 'prefix sums', 'difference array'],
  'tag-prefix-matching-automata': ['KMP法', 'Zアルゴリズム', 'prefix function'],
  'tag-prime-divisor-decomposition': ['素因数分解', '約数列挙', 'prime factorization', 'sieve'],
  'tag-query-sufficient-aggregate': ['動的区間集約', '更新可能な要約', 'dynamic range aggregate'],
  'tag-reachability-bfs': [
    '幅優先探索',
    '深さ優先探索',
    'breadth-first search',
    'BFS',
    'DFS',
    '推移閉包',
    'Warshall法',
  ],
  'tag-randomized-algorithm': [
    '乱択アルゴリズム',
    'Monte Carlo algorithm',
    'Las Vegas algorithm',
    'probabilistic method',
  ],
  'tag-recursive-compressed-string': [
    '圧縮文字列',
    'ランレングス圧縮',
    'RLE',
    'compressed strings',
    'run-length encoding',
  ],
  'tag-reverse-offline': ['逆順処理', 'クエリの逆読み', 'reverse offline processing'],
  'tag-sequence-subsequence-dp': ['部分列DP', '最長増加部分列', 'subsequence DP', 'LIS'],
  'tag-shortest-path': ['最短経路', 'Dijkstra法', 'Bellman–Ford法', 'shortest path'],
  'tag-shortest-path-certificate': [
    '最短路木',
    '経路復元',
    'shortest-path tree',
    'path reconstruction',
  ],
  'tag-spanning-tree-optimization': [
    '最小全域木',
    '最大全域木',
    'minimum spanning tree',
    'maximum spanning tree',
    'Kruskal法',
  ],
  'tag-static-top-tree': ['Top Tree', 'Static Top Tree', 'rake-compress tree'],
  'tag-stochastic-expectation-dp': [
    '期待値DP',
    '確率DP',
    'Markov DP',
    'stochastic dynamic programming',
  ],
  'tag-string-hash-equality': [
    'ローリングハッシュ',
    '文字列ハッシュ',
    'rolling hash',
    'string fingerprint',
  ],
  'tag-string-state-representation': ['文字列アルゴリズム', 'string algorithms'],
  'tag-string-automata': ['文字列オートマトン', 'Aho–Corasick', 'Suffix Automaton', 'SAM'],
  'tag-subset-bitmask-transform': ['部分集合DP', 'bit DP', 'bitmask DP', 'subset transform'],
  'tag-suffix-lcp-index': ['接尾辞配列', 'LCP配列', 'suffix array'],
  'tag-event-sweep': ['走査線', 'イベント走査', 'sweep line', 'event sweep'],
  'tag-symmetry-invariant-normalization': [
    '対称性の利用',
    '不変量',
    'canonicalization',
    'invariant',
    'Burnsideの補題',
    'Pólyaの数え上げ',
  ],
  'tag-tree-aggregation-reroot': ['木DP', '全方位木DP', 'tree DP', 'rerooting DP'],
  'tag-tree-balanced-separator': ['重心分解', 'centroid decomposition', 'tree separator'],
  'tag-tree-metric-diameter': [
    '木の直径',
    '木の中心',
    '最遠点',
    'tree diameter',
    'tree center',
    'eccentricity',
  ],
  'tag-tree-path-decomposition': [
    'HL分解',
    '最小共通祖先',
    'オイラーツアー',
    '仮想木',
    'heavy-light decomposition',
    'HLD',
    'LCA',
    'Euler tour',
    'virtual tree',
  ],
  'tag-trie-prefix': ['Trie', 'トライ木', 'prefix tree'],
  'tag-two-pointers-window': ['尺取り法', 'two pointers', 'sliding window'],
  'tag-witness-impact-localization': [
    '変更影響の局所化',
    'replacement paths',
    'witness-based sensitivity analysis',
  ],
};

export const FINAL_TAG_FORMER_NAMES: Readonly<Record<string, readonly string[]>> = {
  'tag-amortized-heavy-light': [],
  'tag-bounded-enumeration': [],
  'tag-bipartite-structure': [],
  'tag-binary-trie': [],
  'tag-bitset-word-parallel': [],
  'tag-cartesian-tree': [],
  'tag-carry-mixed-radix-dp': [],
  'tag-combinatorial-coefficients': [],
  'tag-constructive-witness': [],
  'tag-coordinate-compression': [],
  'tag-contribution-reordering': [],
  'tag-convex-hull-halfplane': [],
  'tag-convex-hull-trick': [],
  'tag-convolution-fps': [],
  'tag-cyclic-group-order': [],
  'tag-determinant-counting': [],
  'tag-digit-automaton-dp': [],
  'tag-directed-condensation-toposort': [],
  'tag-discrete-convex-marginal': [],
  'tag-divide-enumerate': [],
  'tag-dp-state-equivalence': ['同値性によるDP状態圧縮'],
  'tag-dp-state-transition': [],
  'tag-dp-transition-acceleration': [],
  'tag-dsu-connectivity': [],
  'tag-euler-degree-parity': [],
  'tag-fenwick-weighted-prefix': [],
  'tag-finite-field-extension': [],
  'tag-flow-matching-cut': [],
  'tag-functional-graph-doubling': [],
  'tag-game-grundy-dp': [],
  'tag-game-value-dp': [],
  'tag-grid-table-dp': [],
  'tag-gcd-diophantine': [],
  'tag-geometry-orientation-transform': [],
  'tag-graph-core-peeling': [],
  'tag-graph-model-structure': [],
  'tag-greedy-exchange-order': [],
  'tag-inclusion-exclusion': [],
  'tag-integer-boundary-blocks': [],
  'tag-implicit-binary-tree-arithmetic': [],
  'tag-interactive-protocol': [],
  'tag-interval-partition-dp': [],
  'tag-knapsack-resource': [],
  'tag-lazy-segment-action': [],
  'tag-linear-algebra-xor': [],
  'tag-linear-recurrence-matrix': [],
  'tag-linked-list-index': [],
  'tag-lowlink-critical-structure': [],
  'tag-math-geometry-transformation': [],
  'tag-mo-offline-range': [],
  'tag-model-reduction': [],
  'tag-modular-arithmetic': [],
  'tag-modular-crt': [],
  'tag-monoid-segment-tree': [],
  'tag-monotone-stack-queue': [],
  'tag-monotone-threshold-search': [],
  'tag-ordered-set-heap': [],
  'tag-palindrome-radius': [],
  'tag-persistent-rollback': [],
  'tag-prefix-difference': [],
  'tag-prefix-matching-automata': [],
  'tag-prime-divisor-decomposition': [],
  'tag-query-sufficient-aggregate': ['更新可能な区間集約の設計'],
  'tag-reachability-bfs': [],
  'tag-randomized-algorithm': [],
  'tag-recursive-compressed-string': [],
  'tag-reverse-offline': [],
  'tag-sequence-subsequence-dp': [],
  'tag-shortest-path': [],
  'tag-shortest-path-certificate': [],
  'tag-spanning-tree-optimization': [],
  'tag-static-top-tree': [],
  'tag-stochastic-expectation-dp': [],
  'tag-string-hash-equality': [],
  'tag-string-state-representation': [],
  'tag-string-automata': [],
  'tag-subset-bitmask-transform': [],
  'tag-suffix-lcp-index': [],
  'tag-event-sweep': [],
  'tag-symmetry-invariant-normalization': [],
  'tag-tree-aggregation-reroot': [],
  'tag-tree-balanced-separator': [],
  'tag-tree-metric-diameter': [],
  'tag-tree-path-decomposition': [],
  'tag-trie-prefix': [],
  'tag-two-pointers-window': [],
  'tag-witness-impact-localization': [],
};

export const FINAL_TAG_REPRESENTATIVE_PROBLEM_IDS: Readonly<Record<string, readonly string[]>> = {
  'tag-amortized-heavy-light': ['abc217-e', 'abc329-f', 'abc219-g'],
  'tag-bounded-enumeration': ['abc234-e', 'abc328-e', 'abc353-f', 'abc386-e', 'abc442-g'],
  'tag-bipartite-structure': ['abc451-f', 'abc398-e', 'abc398-g'],
  'tag-binary-trie': ['abc425-g', 'abc254-ex'],
  'tag-bitset-word-parallel': ['abc258-g', 'abc348-f'],
  'tag-cartesian-tree': ['abc275-ex', 'abc420-f'],
  'tag-carry-mixed-radix-dp': ['abc231-e', 'abc466-g'],
  'tag-combinatorial-coefficients': ['abc358-e', 'abc234-f', 'abc217-g'],
  'tag-constructive-witness': ['abc333-e', 'abc239-f', 'abc244-g'],
  'tag-coordinate-compression': ['abc221-e', 'abc287-g', 'abc351-f', 'abc374-f'],
  'tag-contribution-reordering': ['abc233-e', 'abc224-f', 'abc215-g'],
  'tag-convex-hull-halfplane': ['abc251-g', 'abc275-g', 'abc356-g'],
  'tag-convex-hull-trick': ['abc341-g', 'abc289-g', 'abc228-h'],
  'tag-convolution-fps': ['abc392-g', 'abc291-g', 'abc213-h'],
  'tag-cyclic-group-order': ['abc212-g', 'abc222-g', 'abc335-g'],
  'tag-determinant-counting': ['abc216-h', 'abc253-ex', 'abc323-g'],
  'tag-digit-automaton-dp': ['abc235-f', 'abc336-e', 'abc406-e'],
  'tag-directed-condensation-toposort': ['abc291-e', 'abc245-f', 'abc277-ex', 'abc374-g'],
  'tag-discrete-convex-marginal': ['abc389-e', 'abc373-f', 'abc217-h'],
  'tag-divide-enumerate': [
    'abc271-f',
    'abc282-ex',
    'abc267-ex',
    'abc300-g',
    'abc252-ex',
    'abc270-g',
  ],
  'tag-dp-state-equivalence': ['abc375-e', 'abc232-e', 'abc296-ex'],
  'tag-dp-state-transition': ['abc375-e', 'abc253-e', 'abc391-g'],
  'tag-dp-transition-acceleration': ['abc212-e', 'abc353-g', 'abc221-h'],
  'tag-dsu-connectivity': ['abc392-e', 'abc328-f', 'abc314-f'],
  'tag-euler-degree-parity': ['abc286-g', 'abc345-f', 'abc227-h'],
  'tag-fenwick-weighted-prefix': ['abc221-e', 'abc256-f', 'abc287-g'],
  'tag-finite-field-extension': ['abc274-ex', 'abc381-g'],
  'tag-flow-matching-cut': ['abc241-g', 'abc239-g', 'abc231-h'],
  'tag-functional-graph-doubling': ['abc296-e', 'abc212-f', 'abc310-g'],
  'tag-game-grundy-dp': ['abc354-e', 'abc380-f', 'abc297-g'],
  'tag-game-value-dp': ['abc349-e', 'abc303-g', 'abc261-ex'],
  'tag-grid-table-dp': ['abc227-f', 'abc311-e'],
  'tag-gcd-diophantine': ['abc254-f', 'abc340-f', 'abc315-g', 'abc388-f', 'abc306-g'],
  'tag-geometry-orientation-transform': ['abc223-e', 'abc351-e', 'abc220-g'],
  'tag-graph-core-peeling': ['abc266-f', 'abc419-g'],
  'tag-graph-model-structure': ['abc213-e', 'abc235-e', 'abc374-g'],
  'tag-greedy-exchange-order': ['abc214-e', 'abc268-f', 'abc290-ex'],
  'tag-inclusion-exclusion': ['abc455-e', 'abc246-f', 'abc230-g'],
  'tag-integer-boundary-blocks': ['abc230-e', 'abc293-f', 'abc239-ex'],
  'tag-implicit-binary-tree-arithmetic': ['abc220-e', 'abc321-e', 'abc424-e'],
  'tag-interactive-protocol': ['abc305-f', 'abc355-e'],
  'tag-interval-partition-dp': ['abc466-e', 'abc288-f', 'abc233-g'],
  'tag-knapsack-resource': ['abc321-f', 'abc322-e', 'abc383-f'],
  'tag-lazy-segment-action': ['abc340-e', 'abc382-f', 'abc237-g'],
  'tag-linear-algebra-xor': ['abc396-e', 'abc236-f', 'abc212-h'],
  'tag-linear-recurrence-matrix': ['abc293-e', 'abc445-f', 'abc236-g'],
  'tag-linked-list-index': ['abc344-e', 'abc421-f'],
  'tag-lowlink-critical-structure': ['abc334-g', 'abc375-g', 'abc301-ex'],
  'tag-math-geometry-transformation': ['abc358-e', 'abc230-e', 'abc213-h'],
  'tag-mo-offline-range': ['abc242-g', 'abc293-g', 'abc405-g'],
  'tag-model-reduction': ['abc214-e', 'abc233-e', 'abc329-f'],
  'tag-modular-arithmetic': ['abc228-e', 'abc411-e'],
  'tag-modular-crt': ['abc286-f', 'abc423-g', 'abc245-ex'],
  'tag-monoid-segment-tree': ['abc261-e', 'abc223-f', 'abc292-ex'],
  'tag-monotone-stack-queue': ['abc359-e', 'abc379-f', 'abc248-ex'],
  'tag-monotone-threshold-search': ['abc373-e', 'abc236-e', 'abc233-ex'],
  'tag-ordered-set-heap': ['abc281-e', 'abc308-g', 'abc431-g'],
  'tag-palindrome-radius': ['abc398-f', 'abc349-g'],
  'tag-persistent-rollback': ['abc273-e', 'abc453-g', 'abc302-ex'],
  'tag-prefix-difference': ['abc341-e', 'abc430-f', 'abc260-g'],
  'tag-prefix-matching-automata': ['abc430-e', 'abc284-f', 'abc257-g'],
  'tag-prime-divisor-decomposition': ['abc445-e', 'abc259-e', 'abc227-g'],
  'tag-query-sufficient-aggregate': ['abc341-e', 'abc223-f', 'abc453-g'],
  'tag-reachability-bfs': ['abc284-e', 'abc302-f', 'abc317-e', 'abc361-g'],
  'tag-randomized-algorithm': ['abc272-g', 'abc422-e'],
  'tag-recursive-compressed-string': ['abc450-e', 'abc313-e', 'abc417-g'],
  'tag-reverse-offline': ['abc229-e', 'abc346-e', 'abc375-f'],
  'tag-sequence-subsequence-dp': ['abc271-e', 'abc354-f', 'abc240-ex'],
  'tag-shortest-path': ['abc213-e', 'abc237-e', 'abc404-g'],
  'tag-shortest-path-certificate': ['abc252-e', 'abc218-f', 'abc308-ex'],
  'tag-spanning-tree-optimization': ['abc218-e', 'abc282-e', 'abc352-e'],
  'tag-static-top-tree': ['abc351-g', 'abc460-g'],
  'tag-stochastic-expectation-dp': ['abc266-e', 'abc298-e', 'abc226-h'],
  'tag-string-hash-equality': ['abc367-f', 'abc455-g', 'abc274-ex'],
  'tag-string-state-representation': ['abc430-e', 'abc398-f', 'abc362-g'],
  'tag-string-automata': ['abc305-g', 'abc419-f', 'abc433-g'],
  'tag-subset-bitmask-transform': ['abc219-e', 'abc381-f', 'abc295-ex'],
  'tag-suffix-lcp-index': ['abc272-f', 'abc362-g', 'abc268-ex'],
  'tag-event-sweep': ['abc320-e', 'abc231-f', 'abc346-g'],
  'tag-symmetry-invariant-normalization': ['abc242-e', 'abc296-f', 'abc382-g'],
  'tag-tree-aggregation-reroot': ['abc239-e', 'abc220-f', 'abc223-g'],
  'tag-tree-balanced-separator': ['abc359-g', 'abc291-ex'],
  'tag-tree-metric-diameter': ['abc221-f', 'abc267-f', 'abc401-f'],
  'tag-tree-path-decomposition': ['abc294-g', 'abc298-ex', 'abc340-g', 'abc351-g', 'abc405-f'],
  'tag-trie-prefix': ['abc287-e', 'abc353-e', 'abc437-e'],
  'tag-two-pointers-window': ['abc260-e', 'abc250-f', 'abc370-f'],
  'tag-witness-impact-localization': ['abc279-e', 'abc218-f'],
};
