/**
 * 教科書の掲載順。同じ対象・原理を続けて読むための編集上の順序であり、
 * 意味階層と前提DAGから独立した、目次・sidebarだけの表示順として管理する。
 */
export const TEXTBOOK_CHAPTERS = [
  {
    id: 'unit-chapter-modeling',
    introduction:
      '問題を既知の算法へ写すための共通言語を学ぶ。状態の同一視と寄与の分解から始め、探索空間の分割、交換論による貪欲法、単調性による探索へ進む。後半では処理順と総仕事量を設計し、乱択・対話・局面列挙を省くゲーム戦略によって使える情報そのものを考える。以後の各章でも、何を保存する変換なのか、候補を捨ててよい理由は何かをこの章へ戻って確認する。',
    unitIds: [
      'unit-normalization',
      'unit-coordinate-compression',
      'unit-contribution-reordering',
      'unit-bounded-enumeration',
      'unit-backtracking-search',
      'unit-divide-enumeration',
      'unit-recursive-divide-and-conquer',
      'unit-meet-in-the-middle',
      'unit-greedy-exchange',
      'unit-bitwise-greedy-feasibility',
      'unit-constructive-witness',
      'unit-change-impact-localization',
      'unit-monotone-search',
      'unit-two-pointers-window',
      'unit-event-sweep',
      'unit-kinetic-order-maintenance',
      'unit-reverse-offline',
      'unit-parallel-binary-search',
      'unit-decomposition-amortization',
      'unit-amortized-monotone-progress',
      'unit-small-to-large',
      'unit-threshold-heavy-light',
      'unit-randomized-algorithms',
      'unit-randomized-algebraic-fingerprint',
      'unit-interactive-protocol',
      'unit-game-parity-invariant',
      'unit-information-theoretic-query-design',
    ],
  },
  {
    id: 'unit-chapter-query',
    introduction:
      '保持する情報と許す操作からデータ構造を選ぶ。局所的な接続・順序の管理から、累積和、結合的な区間要約、その要約への作用へ進む。静的問い合わせ、窓の移動、疎な座標、過去の版という条件の違いを比較し、最後にbit列とfingerprintによる表現を扱う。DPや木の章では、この章で定めた要約と更新の契約を再利用する。',
    unitIds: [
      'unit-linked-list-index',
      'unit-ordered-set-heap',
      'unit-priority-queue-best-first',
      'unit-ordered-set-multiset',
      'unit-ordered-interval-partition',
      'unit-monotone-stack-queue',
      'unit-cartesian-tree',
      'unit-prefix-aggregate',
      'unit-weighted-prefix-fenwick',
      'unit-monoid-segment-tree',
      'unit-range-monoid-aggregation',
      'unit-finite-function-composition',
      'unit-idempotent-overlap-range-query',
      'unit-swag',
      'unit-segment-tree-canonical-decomposition',
      'unit-static-sorted-range-index',
      'unit-dynamic-segment-tree',
      'unit-range-actions',
      'unit-segment-tree-beats',
      'unit-value-bucket-aggregation',
      'unit-mo-offline-range',
      'unit-persistence-rollback',
      'unit-rollback',
      'unit-persistence',
      'unit-bitset-word-parallel',
      'unit-binary-trie',
      'unit-bitwise-minimax-partition',
      'unit-string-hash',
      'unit-sequence-fingerprint',
    ],
  },
  {
    id: 'unit-chapter-dynamic-programming',
    introduction:
      '未来に必要な情報と依存関係を定め、同じ状態へ到達する履歴をまとめる。グリッド・列・区間・集合の基本状態を比較し、全履歴を持つと大きすぎる場合の発展として境界圧縮へ進む。さらに桁・automatonという状態の形を比較する。確率では何を平均し、ゲームでは誰が選ぶのかを明示する。最後に遷移の共通部分や線形性を取り出し、後の代数・凸最適化の章で使う式へつなぐ。別Unitの技能が先に必要な場合は、各Unitに表示する直接前提から確認する。',
    unitIds: [
      'unit-dp-state-design',
      'unit-dp-grid-table',
      'unit-dp-sequence-interval',
      'unit-dp-sequence',
      'unit-dp-lis',
      'unit-dp-value-range',
      'unit-dp-prefix-partition',
      'unit-dp-interval-composition',
      'unit-dp-interval-expansion',
      'unit-dp-subset-resource',
      'unit-eventual-unbounded-knapsack',
      'unit-dp-subset-state',
      'unit-frontier-profile-dp',
      'unit-steiner-tree-dp',
      'unit-dp-digit-string',
      'unit-digit-dp',
      'unit-automaton-dp',
      'unit-dp-carry-mixed-radix',
      'unit-dp-stochastic',
      'unit-additive-expectation-potential',
      'unit-dp-game',
      'unit-dp-game-value',
      'unit-cyclic-minimax-game',
      'unit-conway-number-games',
      'unit-dp-transition-optimization',
      'unit-linear-recurrence',
    ],
  },
  {
    id: 'unit-chapter-graph',
    introduction:
      '状態と遷移をグラフへ写し、探索による到達性と二部彩色から始めて、距離、連結性の順に構造を調べる。有向グラフではDAGとSCC、無向グラフでは連結成分・橋・全域木を軸に整理し、閉路と次数の構造へ進む。後半は一対一対応から容量付き割当て、費用、双対性へ広げる。matching・flowの各Unitでは、元の問題の制約が頂点・辺・容量のどこに現れるかを確かめる。',
    unitIds: [
      'unit-graph-search',
      'unit-state-graph-search',
      'unit-directional-grid-effect-scan',
      'unit-transitive-closure',
      'unit-bipartite-structure',
      'unit-shortest-path-certificates',
      'unit-weighted-shortest-path',
      'unit-shortest-path-reconstruction',
      'unit-difference-constraints',
      'unit-directed-condensation',
      'unit-dag-topological-processing',
      'unit-scc-condensation',
      'unit-directed-core-peeling',
      'unit-directed-walk-periodicity',
      'unit-two-sat',
      'unit-functional-graph',
      'unit-functional-graph-decomposition',
      'unit-binary-lifting',
      'unit-connectivity',
      'unit-dsu-components',
      'unit-graph-potential-propagation',
      'unit-potential-dsu',
      'unit-monotone-path-contraction',
      'unit-lowlink-critical-structure',
      'unit-spanning-tree-optimization',
      'unit-kruskal-threshold-sweep',
      'unit-cycle-space-basis',
      'unit-graph-core-peeling',
      'unit-graph-core',
      'unit-near-tree-kernelization',
      'unit-euler-degree',
      'unit-euler-trail-circuit',
      'unit-degree-parity-subgraph',
      'unit-flow-matching',
      'unit-bipartite-matching',
      'unit-max-flow-min-cut',
      'unit-flow-lower-bounds',
      'unit-min-cost-flow',
      'unit-weighted-bipartite-matching',
      'unit-min-weight-general-perfect-matching',
      'unit-path-matching-contraction',
      'unit-planar-duality',
    ],
  },
  {
    id: 'unit-chapter-tree',
    introduction:
      '木の一意な経路と部分木への分解を使う。距離・直径から始め、Euler順とLCAで位置関係を表し、path分解と必要頂点だけの圧縮へ進む。次に木DPのまとまりで部分木集約・全方位DP・多項式合成を比較し、重心分解、併合履歴、縮約による最適化へ広げる。軽い子の処理回数、path上の合成、rake・compressがそれぞれ何を高速化するかを区別する。多項式木DPに進むときは代数章の畳み込みを参照する。',
    unitIds: [
      'unit-tree-metric',
      'unit-additive-tree-metric-reconstruction',
      'unit-implicit-binary-tree',
      'unit-tree-decomposition',
      'unit-laminar-interval-containment-tree',
      'unit-tree-euler-flattening',
      'unit-tree-ancestor-lca',
      'unit-heavy-light-decomposition',
      'unit-virtual-tree',
      'unit-tree-aggregation',
      'unit-rooted-tree-aggregation',
      'unit-rerooting',
      'unit-heavy-path-tree-dp',
      'unit-tree-balanced-separators',
      'unit-dsu-merge-tree',
      'unit-tree-precedence-contraction',
      'unit-heavy-light-recursive-dp',
      'unit-static-top-tree',
    ],
  },
  {
    id: 'unit-chapter-string',
    introduction:
      '文字列の一致をどの単位で共有するかを軸に読む。接頭辞の共有と一致長から、周期・回文・接尾辞の順序へ進む。次に読んだprefixを有限状態へまとめ、複数pattern、非決定性、部分文字列集合へ広げる。最後に入力自体が圧縮されている場合の再帰とrunの変化を扱う。rolling fingerprintはデータ構造章、構成したautomaton上の計数はDP章へ接続する。',
    unitIds: [
      'unit-trie-prefix',
      'unit-string-prefix-automata',
      'unit-z-algorithm',
      'unit-string-periodicity',
      'unit-palindrome-radius',
      'unit-suffix-lcp-index',
      'unit-string-automata',
      'unit-finite-pattern-automaton',
      'unit-aho-corasick',
      'unit-automaton-subset-construction',
      'unit-suffix-automaton',
      'unit-recursive-compressed-string',
      'unit-run-length-dynamics',
    ],
  },
  {
    id: 'unit-chapter-number-theory',
    introduction:
      '割り切れる条件から出発し、整数解、合同式、乗法的な周期へ進む。gcdとBézout、CRT、位数と指数化をつなぎ、整数の値を列挙する代わりに同じ振る舞いをする類へまとめる。続いて床関数の境界、Euclidによる格子点計数、有理近似を比較する。発展では到達可能な整数集合、数の拡張、総和篩を扱う。法上の計算は次章の組合せ係数・多項式でも繰り返し使う。',
    unitIds: [
      'unit-prime-divisor',
      'unit-gcd-structure',
      'unit-gcd-diophantine',
      'unit-modular-product-foundations',
      'unit-modular-arithmetic',
      'unit-dynamic-modular-product',
      'unit-modular-congruence',
      'unit-modular-periodicity',
      'unit-multiplicative-order-periods',
      'unit-baby-step-giant-step',
      'unit-cyclic-group-exponent-counting',
      'unit-integer-boundary-blocks',
      'unit-euclidean-floor-sum',
      'unit-rational-approximation',
      'unit-stern-brocot-ancestry',
      'unit-numerical-semigroup-reachability',
      'unit-gaussian-integers-two-squares',
      'unit-finite-field-extension',
      'unit-finite-field-frobenius',
      'unit-min25-sieve',
    ],
  },
  {
    id: 'unit-chapter-combinatorics-algebra',
    introduction:
      '二項係数・包除・反射原理で基本的な重複補正を学び、Möbius反転から部分集合上の変換と畳み込みへ進む。次にPrüfer符号・Burnside・Dilworth・RSK・削除縮約を、構造や対称性を使った数え方として比較する。線形代数を揃えた後、母関数で式を立て、畳み込みとFPSで評価し、高度な係数抽出へ広げる。最後に行列式によるグラフ計数と独立性の構造を扱う。',
    unitIds: [
      'unit-combinatorial-coefficients',
      'unit-inclusion-exclusion',
      'unit-reflection-principle',
      'unit-divisor-mobius-inversion',
      'unit-subset-transforms',
      'unit-subset-convolution',
      'unit-prufer-code',
      'unit-orbit-counting',
      'unit-poset-dilworth-antichain',
      'unit-rsk-young-tableaux',
      'unit-deletion-contraction',
      'unit-monoid-exponentiation',
      'unit-linear-algebra-xor',
      'unit-linear-system-rank',
      'unit-xor-linear-basis',
      'unit-separable-linear-transform',
      'unit-semiring-matrix-exponentiation',
      'unit-generating-functions',
      'unit-labeled-component-decomposition',
      'unit-polynomial-convolution',
      'unit-polynomial-taylor-shift',
      'unit-relaxed-convolution',
      'unit-formal-power-series',
      'unit-polynomial-multipoint-evaluation',
      'unit-bostan-mori',
      'unit-fps-composition-power-projection',
      'unit-generating-function-coefficients',
      'unit-determinant-counting',
      'unit-euler-circuit-counting',
      'unit-matroid-theory',
      'unit-matroid-greedy',
      'unit-linear-matroid-intersection',
    ],
  },
  {
    id: 'unit-chapter-geometry-optimization',
    introduction:
      '位置関係と凸性から、調べる候補を絞る。まず座標・向き・円環順序の判定を揃え、凸包と半平面の共通部分を扱う。直線包絡を境に、幾何的な境界から関数の最適化へ視点を移す。凸最適化のまとまりで限界費用、傾き、順序制約、罰則係数、Monge性を比較し、比率目的の判定問題への変換へ進む。DP・データ構造・flowで得た表現を組み合わせる章として読む。',
    unitIds: [
      'unit-geometry-primitives',
      'unit-cyclic-order-crossing',
      'unit-convex-geometry',
      'unit-convex-boundary-hull',
      'unit-half-plane-constraints',
      'unit-line-envelope',
      'unit-discrete-convex',
      'unit-basic-convex-optimization',
      'unit-separable-convex-marginals',
      'unit-isotonic-regression',
      'unit-slope-trick',
      'unit-lagrangian-relaxation',
      'unit-monge-optimization',
      'unit-fractional-parametric-search',
    ],
  },
] as const;

const textbookIndexById = new Map<string, number>(
  TEXTBOOK_CHAPTERS.flatMap((chapter) => [chapter.id, ...chapter.unitIds]).map((id, index) => [
    id,
    index,
  ]),
);

export const textbookIndex = (unitId: string): number => {
  const index = textbookIndexById.get(unitId);
  if (index === undefined) throw new Error(`TEXTBOOK_UNIT_ORDER_MISSING:${unitId}`);
  return index;
};
