/**
 * 教科書の掲載順。同じ対象・原理を続けて読むための編集上の順序であり、
 * 問題の所属を決める既存の履修順（learning-order）とは独立に管理する。
 * 章内では前提を先に紹介し、章をまたぐ前提は本文のリンクで案内する。
 */
export const TEXTBOOK_CHAPTERS = [
  {
    id: 'unit-chapter-modeling',
    introduction:
      '問題を既知の算法へ写すための共通言語を学ぶ。状態の同一視と寄与の分解から始め、探索空間の分割、交換論による貪欲法、単調性による探索へ進む。後半では処理順と総仕事量を設計し、乱択・対話によって使える情報そのものを考える。以後の各章でも、何を保存する変換なのか、候補を捨ててよい理由は何かをこの章へ戻って確認する。',
    unitIds: [
      'unit-normalization',
      'unit-coordinate-compression',
      'unit-contribution-reordering',
      'unit-bounded-enumeration',
      'unit-backtracking-search',
      'unit-divide-enumeration',
      'unit-recursive-divide-and-conquer',
      'unit-meet-in-the-middle',
      'unit-greedy-exchange',
      'unit-bitwise-greedy-feasibility',
      'unit-binary-tree-ancestor-matching',
      'unit-constructive-witness',
      'unit-change-impact-localization',
      'unit-monotone-search',
      'unit-two-pointers-window',
      'unit-event-sweep',
      'unit-kinetic-order-maintenance',
      'unit-reverse-offline',
      'unit-parallel-binary-search',
      'unit-decomposition-amortization',
      'unit-amortized-monotone-progress',
      'unit-small-to-large',
      'unit-threshold-heavy-light',
      'unit-randomized-algorithms',
      'unit-randomized-algebraic-fingerprint',
      'unit-interactive-protocol',
      'unit-information-theoretic-query-design',
    ],
  },
  {
    id: 'unit-chapter-query',
    introduction:
      '保持する情報と許す操作からデータ構造を選ぶ。局所的な接続・順序の管理から、累積和、結合的な区間要約、その要約への作用へ進む。静的問い合わせ、窓の移動、疎な座標、過去の版という条件の違いを比較し、最後にbit列とfingerprintによる表現を扱う。DPや木の章では、この章で定めた要約と更新の契約を再利用する。',
    unitIds: [
      'unit-linked-list-index',
      'unit-ordered-set-heap',
      'unit-priority-queue-best-first',
      'unit-ordered-set-multiset',
      'unit-ordered-interval-partition',
      'unit-monotone-stack-queue',
      'unit-cartesian-tree',
      'unit-prefix-aggregate',
      'unit-weighted-prefix-fenwick',
      'unit-monoid-segment-tree',
      'unit-range-monoid-aggregation',
      'unit-finite-function-composition',
      'unit-idempotent-overlap-range-query',
      'unit-swag',
      'unit-segment-tree-canonical-decomposition',
      'unit-static-sorted-range-index',
      'unit-dynamic-segment-tree',
      'unit-range-actions',
      'unit-segment-tree-beats',
      'unit-value-bucket-aggregation',
      'unit-mo-offline-range',
      'unit-persistence-rollback',
      'unit-rollback',
      'unit-persistence',
      'unit-bitset-word-parallel',
      'unit-binary-trie',
      'unit-bitwise-minimax-partition',
      'unit-string-hash',
      'unit-sequence-fingerprint',
    ],
  },
  {
    id: 'unit-chapter-dynamic-programming',
    introduction:
      '未来に必要な情報と依存関係を定め、同じ状態へ到達する履歴をまとめる。列・区間・集合という状態の形を比較してから、境界圧縮と桁・automatonの状態へ進む。確率では何を平均し、ゲームでは誰が選ぶのかを明示する。最後に遷移の共通部分や線形性を取り出し、後の代数・凸最適化の章で使う式へつなぐ。automatonの構成は文字列章、Steiner tree DPの距離計算はグラフ章を参照する。',
    unitIds: [
      'unit-dp-state-design',
      'unit-dp-grid-table',
      'unit-dp-sequence-interval',
      'unit-dp-sequence',
      'unit-dp-lis',
      'unit-dp-value-range',
      'unit-dp-prefix-partition',
      'unit-dp-interval-composition',
      'unit-dp-interval-expansion',
      'unit-dp-subset-resource',
      'unit-eventual-unbounded-knapsack',
      'unit-dp-subset-state',
      'unit-steiner-tree-dp',
      'unit-frontier-profile-dp',
      'unit-dp-digit-string',
      'unit-digit-dp',
      'unit-dp-carry-mixed-radix',
      'unit-automaton-dp',
      'unit-dp-stochastic',
      'unit-additive-expectation-potential',
      'unit-dp-game',
      'unit-dp-game-value',
      'unit-cyclic-minimax-game',
      'unit-conway-number-games',
      'unit-dp-transition-optimization',
      'unit-linear-recurrence',
    ],
  },
  {
    id: 'unit-chapter-graph',
    introduction:
      '状態と遷移をグラフへ写し、到達性、距離、連結性の順に構造を調べる。有向グラフではDAGとSCC、無向グラフでは連結成分・橋・全域木を軸に整理し、閉路と次数の構造へ進む。後半は一対一対応から容量付き割当て、費用、双対性へ広げる。matching・flowの各Unitでは、元の問題の制約が頂点・辺・容量のどこに現れるかを確かめる。',
    unitIds: [
      'unit-graph-search',
      'unit-state-graph-search',
      'unit-directional-grid-effect-scan',
      'unit-transitive-closure',
      'unit-shortest-path-certificates',
      'unit-weighted-shortest-path',
      'unit-shortest-path-reconstruction',
      'unit-difference-constraints',
      'unit-directed-condensation',
      'unit-dag-topological-processing',
      'unit-scc-condensation',
      'unit-directed-core-peeling',
      'unit-directed-walk-periodicity',
      'unit-two-sat',
      'unit-functional-graph',
      'unit-functional-graph-decomposition',
      'unit-binary-lifting',
      'unit-connectivity',
      'unit-dsu-components',
      'unit-graph-potential-propagation',
      'unit-potential-dsu',
      'unit-monotone-path-contraction',
      'unit-lowlink-critical-structure',
      'unit-spanning-tree-optimization',
      'unit-kruskal-threshold-sweep',
      'unit-cycle-space-basis',
      'unit-graph-core-peeling',
      'unit-graph-core',
      'unit-near-tree-kernelization',
      'unit-euler-degree',
      'unit-euler-trail-circuit',
      'unit-degree-parity-subgraph',
      'unit-bipartite-structure',
      'unit-flow-matching',
      'unit-bipartite-matching',
      'unit-max-flow-min-cut',
      'unit-flow-lower-bounds',
      'unit-min-cost-flow',
      'unit-weighted-bipartite-matching',
      'unit-min-weight-general-perfect-matching',
      'unit-path-matching-contraction',
      'unit-planar-duality',
    ],
  },
  {
    id: 'unit-chapter-tree',
    introduction:
      '木の一意な経路と部分木への分解を使う。距離・直径から始め、Euler順とLCAで位置関係を表し、部分木集約と全方位DPへ進む。続いてpath・分離点による分解、必要頂点だけの圧縮、併合履歴の木を比較する。後半の木DPでは、軽い子の処理回数、path上の合成、rake・compressがそれぞれ何を高速化するかを区別する。多項式木DPに進むときは代数章の畳み込みを参照する。',
    unitIds: [
      'unit-tree-metric',
      'unit-additive-tree-metric-reconstruction',
      'unit-implicit-binary-tree',
      'unit-tree-decomposition',
      'unit-laminar-interval-containment-tree',
      'unit-tree-euler-flattening',
      'unit-tree-ancestor-lca',
      'unit-tree-aggregation',
      'unit-rooted-tree-aggregation',
      'unit-rerooting',
      'unit-heavy-light-decomposition',
      'unit-virtual-tree',
      'unit-tree-balanced-separators',
      'unit-dsu-merge-tree',
      'unit-tree-precedence-contraction',
      'unit-heavy-light-recursive-dp',
      'unit-heavy-path-tree-dp',
      'unit-static-top-tree',
    ],
  },
  {
    id: 'unit-chapter-string',
    introduction:
      '文字列の一致をどの単位で共有するかを軸に読む。接頭辞の共有と一致長から、周期・回文・接尾辞の順序へ進む。次に読んだprefixを有限状態へまとめ、複数pattern、非決定性、部分文字列集合へ広げる。最後に入力自体が圧縮されている場合の再帰とrunの変化を扱う。rolling fingerprintはデータ構造章、構成したautomaton上の計数はDP章へ接続する。',
    unitIds: [
      'unit-trie-prefix',
      'unit-string-prefix-automata',
      'unit-z-algorithm',
      'unit-string-periodicity',
      'unit-palindrome-radius',
      'unit-suffix-lcp-index',
      'unit-string-automata',
      'unit-finite-pattern-automaton',
      'unit-aho-corasick',
      'unit-automaton-subset-construction',
      'unit-suffix-automaton',
      'unit-recursive-compressed-string',
      'unit-run-length-dynamics',
    ],
  },
  {
    id: 'unit-chapter-number-theory',
    introduction:
      '割り切れる条件から出発し、整数解、合同式、乗法的な周期へ進む。gcdとBézout、CRT、位数と指数化をつなぎ、整数の値を列挙する代わりに同じ振る舞いをする類へまとめる。続いて床関数の境界、Euclidによる格子点計数、有理近似を比較する。発展では到達可能な整数集合、数の拡張、総和篩を扱う。法上の計算は次章の組合せ係数・多項式でも繰り返し使う。',
    unitIds: [
      'unit-prime-divisor',
      'unit-gcd-structure',
      'unit-gcd-diophantine',
      'unit-modular-product-foundations',
      'unit-modular-arithmetic',
      'unit-dynamic-modular-product',
      'unit-modular-congruence',
      'unit-modular-periodicity',
      'unit-multiplicative-order-periods',
      'unit-baby-step-giant-step',
      'unit-cyclic-group-exponent-counting',
      'unit-integer-boundary-blocks',
      'unit-euclidean-floor-sum',
      'unit-rational-approximation',
      'unit-stern-brocot-ancestry',
      'unit-numerical-semigroup-reachability',
      'unit-gaussian-integers-two-squares',
      'unit-finite-field-extension',
      'unit-finite-field-frobenius',
      'unit-min25-sieve',
    ],
  },
  {
    id: 'unit-chapter-combinatorics-algebra',
    introduction:
      '数えたい対象の分解と、それを計算する代数的な表現を結び付ける。係数・全単射・対称性による計数から包除と反転へ進み、線形写像・行列・基底を揃える。母関数で式を立て、畳み込みとFPSで評価し、高度な係数抽出へ広げる。最後に行列式によるグラフ計数と独立性の構造を扱う。式を導く段階と式を高速に計算する段階を分けて説明できることを目指す。',
    unitIds: [
      'unit-combinatorial-coefficients',
      'unit-reflection-principle',
      'unit-prufer-code',
      'unit-orbit-counting',
      'unit-poset-dilworth-antichain',
      'unit-rsk-young-tableaux',
      'unit-deletion-contraction',
      'unit-inclusion-exclusion',
      'unit-divisor-mobius-inversion',
      'unit-subset-transforms',
      'unit-monoid-exponentiation',
      'unit-linear-algebra-xor',
      'unit-linear-system-rank',
      'unit-xor-linear-basis',
      'unit-semiring-matrix-exponentiation',
      'unit-separable-linear-transform',
      'unit-generating-functions',
      'unit-labeled-component-decomposition',
      'unit-polynomial-convolution',
      'unit-subset-convolution',
      'unit-polynomial-taylor-shift',
      'unit-relaxed-convolution',
      'unit-formal-power-series',
      'unit-polynomial-multipoint-evaluation',
      'unit-bostan-mori',
      'unit-generating-function-coefficients',
      'unit-fps-composition-power-projection',
      'unit-determinant-counting',
      'unit-euler-circuit-counting',
      'unit-matroid-theory',
      'unit-matroid-greedy',
      'unit-linear-matroid-intersection',
    ],
  },
  {
    id: 'unit-chapter-geometry-optimization',
    introduction:
      '位置関係と凸性から、調べる候補を絞る。まず座標・向き・円環順序の判定を揃え、凸包と半平面の共通部分を扱う。直線包絡を境に、幾何的な境界から関数の最適化へ視点を移す。限界費用、傾き、順序制約、罰則係数、Monge性を比較し、各条件が探索やDP遷移をどう減らすかを学ぶ。DP・データ構造・flowで得た表現を組み合わせる章として読む。',
    unitIds: [
      'unit-geometry-primitives',
      'unit-cyclic-order-crossing',
      'unit-convex-geometry',
      'unit-convex-boundary-hull',
      'unit-half-plane-constraints',
      'unit-line-envelope',
      'unit-discrete-convex',
      'unit-basic-convex-optimization',
      'unit-separable-convex-marginals',
      'unit-isotonic-regression',
      'unit-slope-trick',
      'unit-fractional-parametric-search',
      'unit-lagrangian-relaxation',
      'unit-monge-optimization',
    ],
  },
] as const;

const textbookIndexById = new Map<string, number>(
  TEXTBOOK_CHAPTERS.flatMap((chapter) => [chapter.id, ...chapter.unitIds]).map((id, index) => [
    id,
    index,
  ]),
);

export const textbookIndex = (unitId: string): number => {
  const index = textbookIndexById.get(unitId);
  if (index === undefined) throw new Error(`TEXTBOOK_UNIT_ORDER_MISSING:${unitId}`);
  return index;
};

/** 既存の内容査読による段階を読者向けに表示する。問題の推定ratingではない。 */
const UNIT_LEVEL_LABELS = ['節案内', '基礎', '標準', '応用', '発展', '専門'] as const;

export const unitLevelLabel = (stageRank: number): string => {
  const label = UNIT_LEVEL_LABELS[stageRank];
  if (label === undefined) throw new Error(`TEXTBOOK_UNIT_LEVEL_UNKNOWN:${String(stageRank)}`);
  return label;
};
