/**
 * 教科書の掲載順。同じ対象・原理を続けて読むための編集上の順序であり、
 * 意味階層の部分木を連続させた読書順。必須の前提DAGとは区別する。
 * 親節と小節を一まとまりにし、独立した応用は節として配置する。
 * 各配列は前提・抽象化の負担・隣接単元との比較を考えて手で編成する。
 * 色・難易度・技能数などのスコアによる自動ソートには置き換えない。
 * textbookIndexは決めた読書順を描画へ渡す位置であり、順序を評価するスコアではない。
 */
export const TEXTBOOK_CHAPTERS = [
  {
    id: 'unit-chapter-modeling',
    introduction:
      'まず全列挙と可逆な探索から正しい基準解を作り、正規化・座標圧縮・寄与分解で扱う対象を減らす。分割統治と半分全列挙で探索空間を分け、単調探索・尺取り・交換論で候補を捨てる理由を学ぶ。構成とゲームの不変量を経て、逆順処理・event走査・償却解析を組み合わせ、多数の判定や局所変更を処理する。対話と情報量、乱択と誤り評価を学んだ後、kineticな順序更新とXOR閾値matchingを複合的な発展として扱う。',
    unitIds: [
      'unit-bounded-enumeration',
      'unit-backtracking-search',
      'unit-normalization',
      'unit-coordinate-compression',
      'unit-contribution-reordering',
      'unit-divide-enumeration',
      'unit-recursive-divide-and-conquer',
      'unit-meet-in-the-middle',
      'unit-monotone-search',
      'unit-two-pointers-window',
      'unit-greedy-exchange',
      'unit-bitwise-greedy-feasibility',
      'unit-constructive-witness',
      'unit-game-parity-invariant',
      'unit-reverse-offline',
      'unit-event-sweep',
      'unit-decomposition-amortization',
      'unit-amortized-monotone-progress',
      'unit-small-to-large',
      'unit-threshold-heavy-light',
      'unit-parallel-binary-search',
      'unit-change-impact-localization',
      'unit-interactive-protocol',
      'unit-information-theoretic-query-design',
      'unit-randomized-algorithms',
      'unit-randomized-algebraic-fingerprint',
      'unit-kinetic-order-maintenance',
      'unit-xor-threshold-matching',
    ],
  },
  {
    id: 'unit-chapter-query',
    introduction:
      '累積和・差分と局所link更新から始め、heap・ordered set・run管理・単調stackで動的な候補を保つ。接頭辞統計をFenwick Treeへ拡張し、結合的な区間要約から関数合成・静的問い合わせ・窓集約・遅延作用へ進む。区間分解を索引や疎な座標に応用し、Cartesian treeでは区間極値を木へ読み替える。bucketとMo、bit列とfingerprintを用途別に比較した後、過去の版と条件付き更新へ進む。最後のSegment Tree Beatsでは遅延作用と償却解析を組み合わせる。',
    unitIds: [
      'unit-prefix-aggregate',
      'unit-linked-list-index',
      'unit-ordered-set-heap',
      'unit-priority-queue-best-first',
      'unit-ordered-set-multiset',
      'unit-ordered-interval-partition',
      'unit-monotone-stack-queue',
      'unit-weighted-prefix-fenwick',
      'unit-monoid-segment-tree',
      'unit-range-monoid-aggregation',
      'unit-finite-function-composition',
      'unit-idempotent-overlap-range-query',
      'unit-swag',
      'unit-segment-tree-canonical-decomposition',
      'unit-static-sorted-range-index',
      'unit-dynamic-segment-tree',
      'unit-range-actions',
      'unit-cartesian-tree',
      'unit-value-bucket-aggregation',
      'unit-mo-offline-range',
      'unit-bitset-word-parallel',
      'unit-binary-trie',
      'unit-bitwise-minimax-partition',
      'unit-string-hash',
      'unit-sequence-fingerprint',
      'unit-persistence-rollback',
      'unit-rollback',
      'unit-persistence',
      'unit-segment-tree-beats',
    ],
  },
  {
    id: 'unit-chapter-dynamic-programming',
    introduction:
      '最小十分状態を定め、グリッド・容量・列・prefix分割・区間・部分集合という基本的な依存構造を比較する。列DPの小節ではLISの支配関係と値域集約を比較する。次に桁上限・automaton・carryによる有限状態化を学び、遷移集約を共通原理として整理して固定線形遷移の累乗へ進む。確率とゲームでは遷移の評価方法を変え、循環局面の後退解析へ広げる。後半は境界圧縮、Steiner木、巨大容量、期待値の状態削減、数ゲームの和を発展として扱う。automatonは文字列章、Steiner木は最短路の単元を先に参照する。',
    unitIds: [
      'unit-dp-state-design',
      'unit-dp-grid-table',
      'unit-dp-subset-resource',
      'unit-dp-sequence-interval',
      'unit-dp-sequence',
      'unit-dp-lis',
      'unit-dp-value-range',
      'unit-dp-prefix-partition',
      'unit-dp-interval-composition',
      'unit-dp-interval-expansion',
      'unit-dp-subset-state',
      'unit-dp-digit-string',
      'unit-digit-dp',
      'unit-automaton-dp',
      'unit-dp-carry-mixed-radix',
      'unit-dp-transition-optimization',
      'unit-linear-recurrence',
      'unit-dp-stochastic',
      'unit-dp-game',
      'unit-dp-game-value',
      'unit-cyclic-minimax-game',
      'unit-frontier-profile-dp',
      'unit-steiner-tree-dp',
      'unit-eventual-unbounded-knapsack',
      'unit-additive-expectation-potential',
      'unit-conway-number-games',
    ],
  },
  {
    id: 'unit-chapter-graph',
    introduction:
      '状態グラフの到達性・二部彩色・連結成分を土台に、等式制約のpotential伝播とweighted DSUを比較する。続いて最短路と経路復元、不等式の差分制約へ進む。有向構造はDAGとpeeling、SCCと2-SAT、一意な後続とdoublingの順に学ぶ。無向構造は全域木・橋・core・cycle space・次数parityを揃えた後、縮約や少数閉路への圧縮へ進む。後半は二部matchingから最大流、下限制約、費用へ進み、平面双対とpath特有の縮約を経て一般重み付きmatchingを扱う。',
    unitIds: [
      'unit-graph-search',
      'unit-state-graph-search',
      'unit-directional-grid-effect-scan',
      'unit-transitive-closure',
      'unit-bipartite-structure',
      'unit-connectivity',
      'unit-dsu-components',
      'unit-graph-potential-propagation',
      'unit-potential-dsu',
      'unit-shortest-path-certificates',
      'unit-weighted-shortest-path',
      'unit-shortest-path-reconstruction',
      'unit-difference-constraints',
      'unit-directed-condensation',
      'unit-dag-topological-processing',
      'unit-directed-core-peeling',
      'unit-scc-condensation',
      'unit-two-sat',
      'unit-functional-graph',
      'unit-functional-graph-decomposition',
      'unit-binary-lifting',
      'unit-spanning-tree-optimization',
      'unit-kruskal-threshold-sweep',
      'unit-lowlink-critical-structure',
      'unit-graph-core-peeling',
      'unit-graph-core',
      'unit-cycle-space-basis',
      'unit-euler-degree',
      'unit-euler-trail-circuit',
      'unit-degree-parity-subgraph',
      'unit-monotone-path-contraction',
      'unit-near-tree-kernelization',
      'unit-directed-walk-periodicity',
      'unit-flow-matching',
      'unit-bipartite-matching',
      'unit-max-flow-min-cut',
      'unit-flow-lower-bounds',
      'unit-min-cost-flow',
      'unit-weighted-bipartite-matching',
      'unit-planar-duality',
      'unit-path-matching-contraction',
      'unit-min-weight-general-perfect-matching',
    ],
  },
  {
    id: 'unit-chapter-tree',
    introduction:
      '一意な経路と距離・直径、完全二分木の対称性を確認し、根付き木DPから全方位DPへ進む。Euler順とLCAで部分木・祖先を索引化し、HLDとvirtual treeでpathと必要頂点へ圧縮する。包含関係や併合履歴を木にする方法を学んだ後、重心分解で均衡分離点による計算量削減を扱う。後半は距離からの木の復元、親先行順序の縮約、多項式木DP、rake・compressによる動的木DP、資源DPを渡すHLRecDPへ進む。多項式木DPでは代数章の畳み込みを先に学ぶ。',
    unitIds: [
      'unit-tree-metric',
      'unit-implicit-binary-tree',
      'unit-tree-aggregation',
      'unit-rooted-tree-aggregation',
      'unit-rerooting',
      'unit-tree-decomposition',
      'unit-tree-euler-flattening',
      'unit-tree-ancestor-lca',
      'unit-heavy-light-decomposition',
      'unit-virtual-tree',
      'unit-laminar-interval-containment-tree',
      'unit-dsu-merge-tree',
      'unit-tree-balanced-separators',
      'unit-additive-tree-metric-reconstruction',
      'unit-tree-precedence-contraction',
      'unit-heavy-path-tree-dp',
      'unit-static-top-tree',
      'unit-heavy-light-recursive-dp',
    ],
  },
  {
    id: 'unit-chapter-string',
    introduction:
      'Trieによる接頭辞共有とZ algorithmによる一致区間の再利用から、周期・回文を調べる。runの局所変化と再帰的な圧縮文字列で、明示展開せずに列を扱う考え方を学ぶ。次に接尾辞順序とLCPによる索引へ進み、有限状態への同値化、Aho–Corasick、非決定性のsubset constructionを扱う。最後にSuffix Automatonで全部分文字列を同値類へ圧縮し、接尾辞配列との表現の違いを比較する。rolling fingerprintはデータ構造章、automaton上の計数はDP章へ接続する。',
    unitIds: [
      'unit-trie-prefix',
      'unit-string-prefix-automata',
      'unit-z-algorithm',
      'unit-string-periodicity',
      'unit-palindrome-radius',
      'unit-run-length-dynamics',
      'unit-recursive-compressed-string',
      'unit-suffix-lcp-index',
      'unit-string-automata',
      'unit-finite-pattern-automaton',
      'unit-aho-corasick',
      'unit-automaton-subset-construction',
      'unit-suffix-automaton',
    ],
  },
  {
    id: 'unit-chapter-number-theory',
    introduction:
      '素因数・gcd・Bézoutから、法上の演算と逆元、CRTへ進む。整数境界の正確な扱いを揃えた後、剰余周期・乗法的位数・巡回群の指数化をつなぎ、BSGSで反復到達時刻を探索する。床和と有理近似ではEuclid互除法による縮小を比較し、Stern–Brocot木の経路へ応用する。発展は数値半群、素体でも使えるFrobenius恒等式、拡大有限体、Gaussian整数、総和篩の順に読む。群の計数には約数反転、総和篩には商一定区間という既習の道具を持ち込む。',
    unitIds: [
      'unit-prime-divisor',
      'unit-gcd-structure',
      'unit-gcd-diophantine',
      'unit-modular-product-foundations',
      'unit-modular-arithmetic',
      'unit-dynamic-modular-product',
      'unit-modular-congruence',
      'unit-integer-boundary-blocks',
      'unit-modular-periodicity',
      'unit-multiplicative-order-periods',
      'unit-cyclic-group-exponent-counting',
      'unit-baby-step-giant-step',
      'unit-euclidean-floor-sum',
      'unit-rational-approximation',
      'unit-stern-brocot-ancestry',
      'unit-numerical-semigroup-reachability',
      'unit-finite-field-frobenius',
      'unit-finite-field-extension',
      'unit-gaussian-integers-two-squares',
      'unit-min25-sieve',
    ],
  },
  {
    id: 'unit-chapter-combinatorics-algebra',
    introduction:
      '組合せ係数と反射原理で直接数える方法を学び、包除から約数・部分集合上の反転へ進む。反復合成と半環行列、線形方程式・XOR基底・分離可能変換を揃え、Prüfer符号・群作用・削除縮約・行列式による計数を比較する。半順序の構造定理を学んだ後、母関数の係数解釈から畳み込み・Taylor shift・FPS・多点評価・有理母関数へ進む。発展では高度な係数抽出、onlineとsubsetの畳み込み、BEST定理、RSK、FPS合成を扱う。最後にmatroidの独立性と交換公理を共通言語にしてgreedyと線形交差を比較する。',
    unitIds: [
      'unit-combinatorial-coefficients',
      'unit-reflection-principle',
      'unit-inclusion-exclusion',
      'unit-divisor-mobius-inversion',
      'unit-subset-transforms',
      'unit-monoid-exponentiation',
      'unit-semiring-matrix-exponentiation',
      'unit-linear-algebra-xor',
      'unit-linear-system-rank',
      'unit-xor-linear-basis',
      'unit-separable-linear-transform',
      'unit-prufer-code',
      'unit-orbit-counting',
      'unit-deletion-contraction',
      'unit-determinant-counting',
      'unit-poset-dilworth-antichain',
      'unit-generating-functions',
      'unit-labeled-component-decomposition',
      'unit-polynomial-convolution',
      'unit-polynomial-taylor-shift',
      'unit-formal-power-series',
      'unit-polynomial-multipoint-evaluation',
      'unit-bostan-mori',
      'unit-generating-function-coefficients',
      'unit-relaxed-convolution',
      'unit-subset-convolution',
      'unit-euler-circuit-counting',
      'unit-rsk-young-tableaux',
      'unit-fps-composition-power-projection',
      'unit-matroid-theory',
      'unit-matroid-greedy',
      'unit-linear-matroid-intersection',
    ],
  },
  {
    id: 'unit-chapter-geometry-optimization',
    introduction:
      '座標・向き・円環順序から凸包と半平面へ進み、幾何的な実行可能領域を表す。直線包絡を幾何と関数の橋渡しとして学ぶ。凸性の節では一次元の最適化から限界値選択・slope trick・順序制約のPAVへ進む。その後、比率目的の判定化、個数制約を罰則へ移すAliens trick、遷移行列のMonge性を独立した節で扱う。最後に二変数の凸区分線形整数最適化で、連続的な候補と整数格子の近傍保証を組み合わせる。DP・データ構造・数論の道具がどの条件で再利用できるかを確認する。',
    unitIds: [
      'unit-geometry-primitives',
      'unit-cyclic-order-crossing',
      'unit-convex-geometry',
      'unit-convex-boundary-hull',
      'unit-half-plane-constraints',
      'unit-line-envelope',
      'unit-discrete-convex',
      'unit-basic-convex-optimization',
      'unit-separable-convex-marginals',
      'unit-slope-trick',
      'unit-isotonic-regression',
      'unit-fractional-parametric-search',
      'unit-lagrangian-relaxation',
      'unit-monge-optimization',
      'unit-two-variable-convex-lattice-optimization',
    ],
  },
] as const;

const textbookIndexById = new Map<string, number>(
  TEXTBOOK_CHAPTERS.flatMap((chapter) => [chapter.id, ...chapter.unitIds]).map((id, index) => [
    id,
    index,
  ]),
);

export const textbookIndex = (unitId: string): number => {
  const index = textbookIndexById.get(unitId);
  if (index === undefined) throw new Error(`TEXTBOOK_UNIT_ORDER_MISSING:${unitId}`);
  return index;
};
